### Análisis: KPI´S

In [8]:
import pandas as pd
import os

# Ruta relativa
ruta = os.path.join('..', 'Data', 'TouristAccommodationClean02022026.csv')

# Leer CSV con encoding correcto
df = pd.read_csv(ruta, encoding='utf-8-sig')

# Ver primeras filas
df.head(3)

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,...,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date,unique_id,city_neighbourhood,ocupacion_30
0,11964,A ROOM WITH A VIEW,Private bedroom in our attic apartment. Right ...,45553,Centro,NaN,Private room,2,2.0,1,...,100.0,100.0,FALSO,75.0,spain,Malaga,31/07/2018,1,Malaga: Centro,23
1,21853,Bright and airy room,We have a quiet and sunny room with a good vie...,83531,Cármenes,Latina,Private room,1,1.0,1,...,80.0,90.0,FALSO,52.0,spain,Madrid,10/01/2020,2,Madrid: Cármenes,30
2,32347,Explore Cultural Sights from a Family-Friendly...,Open French doors and step onto a plant-filled...,139939,San Vicente,Casco Antiguo,Entire home/apt,4,1.0,2,...,100.0,100.0,VERDADERO,142.0,spain,Sevilla,29/07/2019,3,Sevilla: San Vicente,4

#### KPI 1: Tasa de Ocupación Mensual (%)

In [9]:
tasa_ocupacion_mensual = (df['ocupacion_30'].sum() / (len(df) * 30)) * 100
print(f"Tasa de ocupación: {tasa_ocupacion_mensual:.2f}%")

Tasa de ocupación: 56.62%

#### KPI 2: Ciudad con Mayor Ocupación

In [10]:
# Promedio de ocupación por ciudad para 30 días
promedio_ciudad_30 = df.groupby("city")["ocupacion_30"].mean()
promedio_ciudad_30.round(2)

# Ciudad con mayor ocupación
ciudad_mayor_ocupacion = promedio_ciudad_30.idxmax()


print(f"Ciudad con mayor ocupación: {ciudad_mayor_ocupacion}")

Ciudad con mayor ocupación: Madrid

#### KPI 3: Índice de Satisfacción General

In [11]:
indice_satisfaccion = (df["review_scores_rating"] / 10).mean()
print(round(indice_satisfaccion, 2))

91.93

#### KPI 4: Ítem por mayor satisfacción promedio

In [13]:
promedios = df[[
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location"
]].mean().round(2)

item_top = promedios.idxmax()
valor_top = promedios.max()

print(f"Ítem con mayor satisfacción promedio: {item_top} ({valor_top})")

Ítem con mayor satisfacción promedio: review_scores_checkin (96.24)

#### KPI 5: Ciudad con Mayor Satisfacción

In [16]:
columns = [
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location"
]

# Agrupar por ciudad y calcular promedio de cada métrica
avg_scores = df.groupby("city")[columns].mean()

# Crear columna de satisfacción compuesta
avg_scores["satisfaccion_compuesta"] = avg_scores.mean(axis=1)

# Ciudad con mayor satisfacción
top_city = avg_scores["satisfaccion_compuesta"].idxmax()
top_score = avg_scores["satisfaccion_compuesta"].max()

print(f"Ciudad con mayor satisfacción promedio: {top_city} ({top_score:.2f})")

avg_scores.sort_values("satisfaccion_compuesta", ascending=False)

Ciudad con mayor satisfacción promedio: Sevilla (96.73)

,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,satisfaccion_compuesta
city,,,,,,
Sevilla,96.607930,95.748899,97.356828,97.224670,96.718062,96.731278
Menorca,96.375839,92.483221,97.142857,97.852349,95.442177,95.859289
Madrid,95.158637,93.754407,96.554968,96.762632,96.513815,95.748892
Valencia,95.555556,93.038549,97.006803,96.916100,95.510204,95.605442
Malaga,95.069767,94.162791,96.488372,96.348837,94.790698,95.372093
Mallorca,94.499504,94.271556,96.689792,96.504950,94.445545,95.282269
Barcelona,93.421174,92.027714,95.615171,95.441109,95.312355,94.363505
Girona,93.725910,91.918977,95.455520,95.604278,94.570815,94.255100