In [69]:
# ======================================================
# LIBRERÍAS
# ======================================================

import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 100)

print("✅ Librerías cargadas")

✅ Librerías cargadas

In [70]:
# ======================================================
# CONFIGURACIÓN
# ======================================================

# Ruta del proyecto

DATA_PATH = "../Data/2026-07-20_ECF_2021_ecf_2021.dta"

In [71]:
# ======================================================
# CARGA DEL DATASET
# ======================================================

df = pd.read_stata(

    DATA_PATH,

    convert_categoricals=True

)

print(df.shape)

(7764, 429)

In [72]:
# ======================================================
# INFORMACIÓN GENERAL
# ======================================================

print("="*70)
print("DATASET ORIGINAL")
print("="*70)

print(f"Observaciones : {df.shape[0]:,}")
print(f"Variables     : {df.shape[1]}")

display(df.head())

======================================================================
DATASET ORIGINAL
======================================================================
Observaciones : 7,764
Variables     : 429

,a01,a02,a0000,a0400,a04,a0800,a0100,a0320,a1030,a1040,a0910,a1100,a1200,a1300,a1400,a1410,a1420a,a1420b,a1420c,a1420d,a1420e,a1420f,a1420g,a1500,a1510,a1600,a1520,a1530,a2000,a1700,a1710,a1900,a2100,a2200,a2300,a2500,a2400,a2600,a2700,b0100,b0110a,b0110b,b0110c,b0110d,b0110e,b0110f,b0110g,b0120a,b0120b,b0120c,b0120d,b0120e,b0120f,b0130a,b0130b,b0130c,b0208,b0308,b0408,b0201,b0301,b0401,b0202,b0302,b0402,b0203,b0303,b0403,b0204,b0304,b0404,b0205,b0305,b0405,b0206,b0306,b0406,b0207,b0307,b0407,b0209,b0309,b0409,b0210,b0310,b0410,b0212,b0312,b0412,b1100a,b1100b,b1100c,b1100d,b1100e,b1100f,b1100g,b1100i,b1100h,b0502,b0503,b0600,b0720a,b0720b,b0720c,b0720d,b0720e,b0720f,b0720g,b0720h,b0720i,b0710a,b0710b,b0710c,b0710d,b0710e,b0710f,b0710g,b0710h,b0710i,b1000a,b1000b,b1000c,b1000d,b1000e,b1000f,b1000g,b1000h,b1000i,b1000j,b1103,b1201,b1203a,b1203b,b1203c,b1203d,b1203e,b1203f,b1203g,b1204a,b1204b,b1204c,b1204d,b1204e,b1204f,b1204g,b1205a,b1205b,b1205c,b1205d,b1205e,b1206a,b1206b,b1206c,b1206d,b1206e,b1207a,b1207b,b1207c,b1208a,b1208b,b1208c,b1208d,b1209a,b1209b,b1209c,b1209d,b1230a,b1230b,b1230c,b1230d,b1230e,b1230f,b1230g,b1230h,c0100,c0200a,c0200b,c0200c,c0200d,c0200e,c0200f,c0200g,c0200h,c0200i,c0200j,c0200k,c0300,c0500,c0600a,c0600b,c0600c,c0600d,c0600e,c0600f,c0600g,c0600h,c0600i,c0600j,c0600k,c0400a,c0400b,c0400c,c0400d,c0400e,c0400f,c0400g,c0400h,c0400i,c0400j,c0400k,c0400l,c0400m,c0400n,d0101,d0104,d0110,d0113,d0102,d0114,d0115,d0117,d0103,d0116,d0105,d0106,d0107,d0108,d0109,d0111,d0112,d0300,d0400,d0500,d0600,d0610a,d0610b,d0610c,d0610d,d0610e,e0100,e0500,e0600,e0700,e0800,e0900,e1001,e1002,e1003,e1004,e1005,e1200,e1101,e0401,e0402,e0300,e1400,e1500,e1600,e1701,e1702,e1800,e1300,i0100,i0200a,i0200b,i0200c,i0200d,i0200e,i0200h,i0200f,i0200g,i0200j,i0300,i0500a,i0500b,i0500c,i0500d,i0500e,i0500f,i0500g,i0500h,i0500i,i0500k,i0500j,i0800,i0510,i0520a,i0520b,i0520c,i0520e,i0520f,i0520d,i0520g,i0601,i0602,i0700,i0900,i1000,i0400a,i0400b,i0400c,i0400d,i0400e,j0100,j0110,j0200,j0300a,j0300b,j0300c,j0300d,j0300e,j0300f,j0300g,j0300h,j0300i,j0300j,j0300k,j0300l,j0300m,j0300n,j0300p,j0300o,j0400,j0500,j0600,j0700,j0800a,j0800b,j0800c,j0800d,j0800e,j0800f,j0800h,j0800g,j0810,j0900a,j0900b,j0900c,j0900d,j0910a,j0910b,j0910c,j0910d,j0910e,j0910f,j0920,j1000,j1100,j1201,j1202,j1203,j1300,j1400,j1600,k1908,k1901,k1902,k1903,k1904,k1905,k1906,k1907,k1909,k1910,k1912,k0100,k0500,k0600,k0700,k0800,k0900,k1001,k1002,k1003,k1004,k1005,k1200,k1101,k0401,k0402,k0300,k1400,k1500,k1600,k1701,k1702,k1800,k1300,k2020,negativa_pmi,tmp_e0401,age,f0900a,f1000a,weight,a0940,a0930,a0300,a0310,ccaaf,a0930_b,a0950,f1100,f1200,f1200_b,f1300,a0900b,a0900c,a0900d,a0900e,a0900f,a0900l,a0900j,a0900h,a0900g,a0900i,a0900a,a0900k,a1800,a0200,f0900b,f1000b,f0900c,f1000c,f0900d,f1000d,f0900e,f1000e,ID
0,2022,6,Mujer,1982,40,No ha lugar (no aplica filtro),España,No,Casado,Gananciales,3,"g. Diplomaturas universitarias, grados universitarios de 240 créditos y similares","e. Otras ciencias sociales (Psicología, Sociología, Periodismo e Información...) y ciencias jurí...",No ha lugar (no aplica filtro),d. Los suficientes para llenar dos estanterías (entre 101 y 200 libros),Sí,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,b. Trabaja por cuenta ajena,No tengo una segunda situación laboral,No ha lugar (no aplica filtro),A tiempo parcial,No ha lugar (no aplica filtro),Indefinido,No ha lugar (no aplica filtro),21,No,50,80,No ha lugar (no aplica filtro),c. Primera etapa de Educación Secundaria y similar,b. Trabaja por cuenta ajena,k. Dedicado a labores del hogar,"h. Operadores de instalaciones y maquinaria, y montadores",Sí,No mencionado,Mencionado,No mencionado,Mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,Mencionado,No mencionado,Sí,No,No,Sí,Sí,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,Sí,Sí,Sí,Sí,No,Sí,No,No,Sí,No,No,Sí,No,No,No mencionado,No ha lugar (no aplica filtro),No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,Mencionado,Préstamo personal,Conjunta,b. Consideré/ consideramos varias opciones de una única empresa o institución,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No,No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,Mencionado,No mencionado,No mencionado,1 (MUY MAL),Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,60,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),5-Siempre,5-Siempre,5-Siempre,3-En ocasiones,2-Poco,4-Bastante,4-Bastante,5-Completamente,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,2-Bastante en desacuerdo,3-Ni de acuerdo ni en desacuerdo,5-Completamente de acuerdo,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),20,4,1,3,1,1,3- Medios,200.0,a. Más de lo que podrían comprar hoy con su parte del dinero,0.0,120.0,Exactamente 110 euros,Verdadero,Verdadero,No sabe,Verdadero,1 Nada Seguro,Verdadero,Fondo 1 (Azul),"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",18,500.0,1.0,30.0,"d. Aproximadamente, 15 de cada 100 personas que utilizan esta medicación desarrollan un sarpullido.",Tipo de interés del 1%,Tipo de interés del 3%,a. La economía ha crecido en un 1%,5,a. Propiedad por compra (mayoritariamente) –incluye permuta y construcción propia,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,2007,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Sí,Para financiar la compra de la vivienda principal,450,80,No,1,2,5,1,1,Sí,No,Sí,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,g. Un año o más,800,Un mes,1500,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Todas las personas seleccionadas forman parte del hogar,No mencionado,No mencionado,No mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No,No,No,d. Entre 27.001 y 47.000 euros,-5,No lo he consultado hasta el momento de realizar la entrevista,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),69.70,40,Mencionado,Mencionado,6814.125977,Hombre,44.0,No ha lugar (no aplica filtro),-98.0,Andalucía,No ha lugar (no aplica filtro),15.0,Titular muestral,40.0,No ha lugar (no aplica filtro),Mujer,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.0,Andalucía,Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,1.0
1,2022,3,Mujer,1967,54,No ha lugar (no aplica filtro),España,No,Soltero,No ha lugar (no aplica filtro),2,"h. Grados universitarios de más de 240 créditos, licenciaturas, másteres y similares","e. Otras ciencias sociales (Psicología, Sociología, Periodismo e Información...) y ciencias jurí...",No ha lugar (no aplica filtro),a. Ninguno o muy pocos (entre 0 y 10 libros),No,No mencionado,Mencionado,Mencionado,Mencionado,Mencionado,No mencionado,No mencionado,b. Trabaja por cuenta ajena,No tengo una segunda situación laboral,No ha lugar (no aplica filtro),A tiempo completo,No ha lugar (no aplica filtro),No contesta,No ha lugar (no aplica filtro),27,No,20,10,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),k. Dedicado a labores del hogar,"h. Operadores de instalaciones y maquinaria, y montadores",Sí,Mencionado,Mencionado,Mencionado,Mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,Sí,No,Sí,Sí,No,Sí,No,No,Sí,Sí,No,Sí,No,No,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No,No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,3 (REGULAR),Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,67,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),3-En ocasiones,5-Siempre,4-Con frecuencia,4-Con frecuencia,2-Poco,2-Poco,2-Poco,4-Bastante,2-Bastante en desacuerdo,2-Bastante en desacuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,1-Completamente en desacuerdo,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),50,0,2,0,8,0,3- Medios,200.0,c. Menos de lo que podrían comprar hoy,0.0,100.0,No sabe,No sabe,Verdadero,No sabe,Falso,3,Falso,Fondo 2 (Verde),"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",24,No sabe,3.0,30.0,"b. Para aplicaciones en la piel, utilizar solo un 15% de la dosis recomendada.",Tipo de interés del 3%,Tipo de interés del 1%,e. El valor del euro ha crecido en un 1%,1 - Nada Seguro,b. Propiedad por herencia o regalo (mayoritariamente),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Sí,0,2,1,6,1,Sí,No,Sí,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,"c. Por lo menos un mes, pero menos de tres meses",300,Un mes,0,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Ambos,No,No ha lugar (no aplica filtro),No,No,Sí,d. Entre 27.001 y 47.000 euros,-98,No lo he consultado hasta el momento de realizar la entrevista,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),88.47,54,Mencionado,Mencionado,3277.015137,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),-98.0,Canarias,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Titular muestral,54.0,No ha lugar (no aplica filtro),Mujer,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,Canarias,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),2.0

In [73]:
# ======================================================
# INFORMACIÓN DE VARIABLES
# ======================================================

variables = pd.DataFrame({
    "Variable": df.columns,
    "Tipo": df.dtypes.astype(str)
})

display(variables.head(20))

       Variable      Tipo
a01         a01     int16
a02         a02      int8
a0000     a0000  category
a0400     a0400  category
a04         a04  category
a0800     a0800  category
a0100     a0100  category
a0320     a0320  category
a1030     a1030  category
a1040     a1040  category
a0910     a0910      int8
a1100     a1100  category
a1200     a1200  category
a1300     a1300  category
a1400     a1400  category
a1410     a1410  category
a1420a   a1420a  category
a1420b   a1420b  category
a1420c   a1420c  category
a1420d   a1420d  category

In [74]:
# ======================================================
# VARIABLES COMUNES
# ======================================================

COMMON_VARS = [

]

In [75]:
# ======================================================
# FINANCIAL BEHAVIOUR
# ======================================================

FINANCIAL_BEHAVIOUR = [

]

In [76]:
# ======================================================
# ATTITUDES
# ======================================================

ATTITUDES = [

]

In [77]:
# ======================================================
# HOUSING
# ======================================================

HOUSING = [

]

In [78]:
# ======================================================
# FRAGILITY
# ======================================================

FRAGILITY = [

]

In [79]:
# ======================================================
# BACKGROUND
# ======================================================

BACKGROUND = [

]

In [80]:
# ======================================================
# FINANCIAL COMPETENCIES
# ======================================================

FINANCIAL_COMPETENCIES = [

]

In [81]:
# ======================================================
# DICCIONARIO DE BLOQUES
# ======================================================

VARIABLE_BLOCKS = {

    "COMMON": COMMON_VARS,

    "BEHAVIOUR": FINANCIAL_BEHAVIOUR,

    "ATTITUDES": ATTITUDES,

    "HOUSING": HOUSING,

    "FRAGILITY": FRAGILITY,

    "BACKGROUND": BACKGROUND,

    "COMPETENCIES": FINANCIAL_COMPETENCIES

}

In [82]:
# ======================================================
# CREACIÓN DEL MASTER DATASET
# ======================================================

MASTER_VARIABLES = []

for block in VARIABLE_BLOCKS.values():

    MASTER_VARIABLES.extend(block)

MASTER_VARIABLES = list(dict.fromkeys(MASTER_VARIABLES))

print(f"Variables seleccionadas: {len(MASTER_VARIABLES)}")

Variables seleccionadas: 0

In [83]:
master_df = df[MASTER_VARIABLES].copy()

In [84]:
# ======================================================
# COMPROBACIONES
# ======================================================

print("="*70)

print(f"Observaciones : {master_df.shape[0]:,}")

print(f"Variables     : {master_df.shape[1]}")

print("="*70)

======================================================================
Observaciones : 7,764
Variables     : 0
======================================================================

In [85]:
missing = (
    master_df
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(missing.head(30))

Series([], dtype: float64)

In [86]:
# ======================================================
# EXPORTACIÓN
# ======================================================

master_df.to_csv(

    "../Data/2026-07-20_ECF_2021_MasterDataset.csv",

    index=False

)

print("✅ Dataset exportado")

✅ Dataset exportado

In [87]:
# ======================================================
# RESUMEN
# ======================================================

print("="*80)

print("MASTER DATASET CREADO")

print("="*80)

for bloque, variables in VARIABLE_BLOCKS.items():

    print(f"{bloque:<20} {len(variables):>4} variables")

print("-"*80)

print(f"TOTAL VARIABLES : {master_df.shape[1]}")

print(f"TOTAL FILAS     : {master_df.shape[0]:,}")

================================================================================
MASTER DATASET CREADO
================================================================================
COMMON                  0 variables
BEHAVIOUR               0 variables
ATTITUDES               0 variables
HOUSING                 0 variables
FRAGILITY               0 variables
BACKGROUND              0 variables
COMPETENCIES            0 variables
--------------------------------------------------------------------------------
TOTAL VARIABLES : 0
TOTAL FILAS     : 7,764