In [1]:
import pandas as pd
from pathlib import Path

# 1. ECF 2021

In [ ]:

data_dir = Path("../Data")
input_file = data_dir / "2026-07-20_ECF_2021_ecf_2021.dta"


df_ecf_2021 = pd.read_stata(input_file)


df_ecf_2021.head()

,a01,a02,a0000,a0400,a04,a0800,a0100,a0320,a1030,a1040,...,a0200,f0900b,f1000b,f0900c,f1000c,f0900d,f1000d,f0900e,f1000e,ID
0,2022,6,Mujer,1982,40,No ha lugar (no aplica filtro),España,No,Casado,Gananciales,...,Andalucía,Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,1.0
1,2022,3,Mujer,1967,54,No ha lugar (no aplica filtro),España,No,Soltero,No ha lugar (no aplica filtro),...,Canarias,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),2.0
2,2022,2,Hombre,1967,54,No ha lugar (no aplica filtro),España,No,Viudo,No ha lugar (no aplica filtro),...,Extremadura,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),3.0
3,2022,5,Hombre,1974,48,No ha lugar (no aplica filtro),España,No,Casado,Gananciales,...,Canarias,Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,4.0
4,2022,6,Hombre,1972,49,No ha lugar (no aplica filtro),España,No,Soltero,No ha lugar (no aplica filtro),...,"Balears, Illes",No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),5.0

In [5]:
lector = pd.read_stata(input_file, iterator=True)

etiquetas = lector.variable_labels()

list(etiquetas.items())[:20]

df_etiquetas = pd.DataFrame(
    etiquetas.items(),
    columns=["variable", "descripcion"]
)

display(df_etiquetas.head(30))

   variable                                        descripcion
0       a01                         a01: anio de la entrevista
1       a02                          a02: mes de la entrevista
2     a0000  a0000: es requisito que pregunte su genero, es...
3     a0400                          a0400: en que anio nacio?
4       a04                                a04: edad calculada
5     a0800         a0800: me podria decir su edad aproximada?
6     a0100                          a0100: en que pais nacio?
7     a0320  a0320: nacio alguno de sus padres fuera de esp...
8     a1030             a1030: cual es su estado civil actual?
9     a1040   a1040: cual es su regimen economico matrimonial?
10    a0910  a0910: con cuantas personas vive habitualmente...
11    a1100  a1100: cual es el mayor nivel de formacion que...
12    a1200  a1200: cual es el contenido del titulo univers...
13    a1300  a1300: cual es el contenido del titulo de form...
14    a1400  a1400: cuantos libros habia, donde vivia cuand...
15    a1410  a1410: le explicaron sus padres como encargars...
16   a1420a  a1420a: ha recibido formación financiera de ot...
17   a1420b  a1420b: ha recibido formación financiera de ot...
18   a1420c  a1420c: ha recibido formación financiera de ot...
19   a1420d  a1420d: ha recibido formación financiera de ot...
20   a1420e  a1420e: ha recibido formación financiera de ot...
21   a1420f  a1420f: ha recibido formación financiera de ot...
22   a1420g  a1420g: ha recibido formación financiera de ot...
23    a1500        a1500: cual es su situacion laboral actual?
24    a1510  a1510. si tiene más de una situacion laboral, ...
25    a1600  a1600: cual es el nivel de estudios que esta c...
26    a1520        a1520: trabaja a tiempo completo o parcial?
27    a1530                 a1530: tiene empleados a su cargo?
28    a2000         a2000: que tipo de contrato laboral tiene?
29    a1700                 a1700: ha trabajado alguna vez...?

In [3]:
del lector

In [4]:
# consultar variable concreta

df_etiquetas[df_etiquetas["variable"] == "a1100"]

   variable                                        descripcion
11    a1100  a1100: cual es el mayor nivel de formacion que...

In [5]:
# buscar por palabras

df_etiquetas[
    df_etiquetas["descripcion"]
    .str.contains(
        "hipoteca|préstamo|depósito|ahorro",
        case=False,
        na=False,
        regex=True
    )
]

    variable                                        descripcion
56     b0208  b0208: ha oido hablar de las cuentas o deposit...
58     b0408  b0408: en los ultimos 2 anios ha contratado,(....
59     b0201           b0201: ha oido hablar de las hipotecas?
60     b0301  b0301: en la actualidad tiene, personal o conj...
61     b0401  b0401: en los ultimos 2 anios ha contratado,(....
90    b1100b  b1100b: que productos son exclusivamente suyos...
91    b1100c  b1100c: que productos son exclusivamente suyos...
121   b1000c  b1000c: ha estado los ultimos 12 meses: c. aho...
131   b1203a  b1203a: con que productos tuve desavenencias?:...
158   b1208a  b1208a: que tipo de desavenencia sobre depósit...
159   b1208b  b1208b: que tipo de desavenencia sobre depósit...
160   b1208c  b1208c: que tipo de desavenencia sobre depósit...
161   b1208d  b1208d: que tipo de desavenencia sobre depósit...
211   c0400m  c0400m: actuales fuentes ingresos?: m. ahorros...
236   d0610c  d0610c: como utilizaria ese ingreso extra en l...
243    e0800  e0800: ingresa eur100 en una cuenta de ahorro ...
250    e1200  e1200: una hipoteca a 15 anios requiere normal...
266   i0200d  i0200d: por que alquilar? d. no reuno las cond...
267   i0200e  i0200e: por que alquilar? e. no podria hacer f...
276   i0500d  i0500d: por que comprar? d. ir amortizando la ...
293    i0601    i0601: tienen hipotecada su vivienda principal?
294    i0602  i0602: con que objetivos hipotecaron su vivien...
295    i0700  i0700: cual es el importe mensual que pagan po...
296    i0900  i0900: que porcentaje del precio de compra de ...
306   j0300a  j0300a: gastos exceden ingresos?: a. utilizar ...
310   j0300e  j0300e: gastos exceden ingresos?: e. hipotecar...
311   j0300f  j0300f: gastos exceden ingresos?: f. ampliar u...
354    k1908  k1908: ha oido hablar de las cuentas o deposit...
355    k1901            k1901: ha oido hablar de las hipotecas?
369    k0800  k0800: ingresa eur100 en una cuenta de ahorro ...
376    k1200  k1200: una hipoteca a 15 anios requiere normal...

In [6]:
# ver solo las variables demográficas

variables_demograficas = [
    "a0000",  # género
    "a04",    # edad
    "a0100",  # país de nacimiento
    "a1030",  # estado civil
    "a1100"   # educación
]

display(df_ecf_2021[variables_demograficas].head())

,a0000,a04,a0100,a1030,a1100
0,Mujer,40,España,Casado,"g. Diplomaturas universitarias, grados univers..."
1,Mujer,54,España,Soltero,h. Grados universitarios de más de 240 crédito...
2,Hombre,54,España,Viudo,d. Segunda etapa de Educación Secundaria y sim...
3,Hombre,48,España,Casado,d. Segunda etapa de Educación Secundaria y sim...
4,Hombre,49,España,Soltero,b. Educación primaria Incluye sabe leer y escr...

In [7]:
# buscar por trabajo

df_etiquetas[
    df_etiquetas["descripcion"]
    .str.contains(
        "situación laboral|trabaja|empleo|ocupación",
        case=False,
        na=False,
        regex=True
    )
]

    variable                                        descripcion
26     a1520        a1520: trabaja a tiempo completo o parcial?
29     a1700                 a1700: ha trabajado alguna vez...?
30     a1710         a1710. cuantos años ha trabajado en total?
199   c0400a  c0400a: actuales fuentes ingresos?: a. seguro ...
200   c0400b  c0400b: actuales fuentes ingresos?: b. seguro ...
348    j1201  j1201: ultimos 12 meses,algun miembro de su ho...
349    j1202  j1202: ultimos 12 meses,algun miembro de su ho...

# 2. ECF 2016

In [2]:
ruta = r"C:\Users\elisa\Documents\Simulador\ProjecteData\Equip_32\Data\2026-07-20_ECF_2016_ecf_2016.dta"

df_ecf_2016 = pd.read_stata(ruta)

df_ecf_2016.head()

,a01,a02,a0000,a0100,a0400,a04,a0800,a0900a,a0900b,a0900c,...,ccaaf,age,j0300p,j0800h,a0300,ID,a1800,g0800,a0200,weight
0,2016,12,0,1,1998,18,-98,0,0,0,...,1,18,-98,-98,-98,1114,-98,-98,1,5446.342285
1,2016,10,0,1,1982,33,-98,0,1,1,...,1,33,-98,0,-98,1136,45,-98,1,6316.522461
2,2016,10,1,1,1967,49,-98,0,1,1,...,1,49,-98,0,-98,3783,63,-98,1,6204.820801
3,2016,10,0,1,1962,54,-98,0,1,0,...,1,54,-98,-98,-98,171,95,-98,1,4990.569336
4,2016,10,0,1,1952,64,-98,0,1,0,...,1,64,-98,-98,-98,2945,77,-98,1,6204.776367