In [ ]:
import warnings
import pandas as pd
from pathlib import Path

In [ ]:


warnings.filterwarnings(
    "ignore",
    message="Workbook contains no default style"
)

# 1. Población por edad y sexo
df_poblacion = pd.read_excel(
    "../Data/ine/36643.xlsx",
    header=6
)

# 2. Saldo vegetativo
df_saldo_vegetativo = pd.read_excel(
    "../Data/ine/INE_saldo_vegetativo_2026_2075.xlsx",
    header=None,
    skiprows=6,
    names=[
        "periodo",
        "saldo_vegetativo_por_mil"
    ]
)

# Convertir ambas columnas a números
df_saldo_vegetativo["periodo"] = pd.to_numeric(
    df_saldo_vegetativo["periodo"],
    errors="coerce"
)

df_saldo_vegetativo["saldo_vegetativo_por_mil"] = pd.to_numeric(
    df_saldo_vegetativo["saldo_vegetativo_por_mil"],
    errors="coerce"
)

# Seleccionar solo 2026-2036
df_saldo_vegetativo = (
    df_saldo_vegetativo.loc[
        df_saldo_vegetativo["periodo"].between(
            2026,
            2036
        )
    ]
    .copy()
)

# Año como número entero
df_saldo_vegetativo["periodo"] = (
    df_saldo_vegetativo["periodo"].astype(int)
)

# Ordenar cronológicamente
df_saldo_vegetativo = (
    df_saldo_vegetativo
    .sort_values("periodo")
    .reset_index(drop=True)
)


# 3. Migración neta
df_migracion_neta = pd.read_excel(
    "../Data/ine/INE_migracion_neta_2026_2075.xlsx",
    header=None,
    skiprows=6,
    names=[
        "periodo",
        "tasa_migracion_neta"
    ]
)

# convertir datos
df_migracion_neta["periodo"] = pd.to_numeric(
    df_migracion_neta["periodo"],
    errors="coerce"
)

df_migracion_neta["tasa_migracion_neta"] = pd.to_numeric(
    df_migracion_neta["tasa_migracion_neta"],
    errors="coerce"
)

# decada ordenada
df_migracion_neta = (
    df_migracion_neta.loc[
        df_migracion_neta["periodo"].between(
            2026,
            2036
        )
    ]
    .copy()
)

df_migracion_neta["periodo"] = (
    df_migracion_neta["periodo"].astype(int)
)

df_migracion_neta = (
    df_migracion_neta
    .sort_values("periodo")
    .reset_index(drop=True)
)


display(df_poblacion.head())
display(df_saldo_vegetativo.head())
display(df_migracion_neta.head())

,,2076,2075,2074,2073,2072,2071,2070,2069,2068,...,2035,2034,2033,2032,2031,2030,2029,2028,2027,2026
0,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Todas las edades,5.297299e+07,5.302801e+07,5.308861e+07,5.315315e+07,5.322143e+07,5.329357e+07,5.336974e+07,5.344987e+07,5.353358e+07,...,5.288414e+07,5.265876e+07,5.240291e+07,5.211205e+07,5.178245e+07,5.141203e+07,5.100118e+07,5.055393e+07,5.007877e+07,49590099.0
2,0 años,3.555469e+05,3.548414e+05,3.539143e+05,3.527670e+05,3.514238e+05,3.499194e+05,3.482985e+05,3.466060e+05,3.448875e+05,...,3.613875e+05,3.569122e+05,3.524054e+05,3.478817e+05,3.433373e+05,3.387731e+05,3.342223e+05,3.297576e+05,3.255249e+05,323425.0
3,1 año,3.584631e+05,3.575461e+05,3.564309e+05,3.551247e+05,3.536552e+05,3.520659e+05,3.504023e+05,3.487126e+05,3.470484e+05,...,3.621268e+05,3.579681e+05,3.538438e+05,3.497394e+05,3.456374e+05,3.415435e+05,3.374931e+05,3.335851e+05,3.316380e+05,324651.0
4,2 años,3.611875e+05,3.600844e+05,3.588126e+05,3.573823e+05,3.558296e+05,3.541985e+05,3.525382e+05,3.509025e+05,3.493458e+05,...,3.632257e+05,3.594418e+05,3.557263e+05,3.520507e+05,3.484016e+05,3.447869e+05,3.412688e+05,3.395938e+05,3.329214e+05,330814.0

   periodo  saldo_vegetativo_por_mil
0     2026                 -2.542558
1     2027                 -2.529663
2     2028                 -2.517906
3     2029                 -2.507789
4     2030                 -2.504546

   periodo  tasa_migracion_neta
0     2026            12.348410
1     2027            11.973166
2     2028            11.325929
3     2029            10.531064
4     2030             9.683639

In [16]:
print("Población:", df_poblacion.shape)
print("Saldo vegetativo:", df_saldo_vegetativo.shape)
print("Migración neta:", df_migracion_neta.shape)

Población: (315, 52)
Saldo vegetativo: (11, 2)
Migración neta: (11, 2)

In [17]:
# renombra columna edad
df_poblacion = df_poblacion.rename(columns={df_poblacion.columns[0]: "edad"})

# limpiar espacios
df_poblacion["edad"] = df_poblacion["edad"].astype(str).str.strip()

# bloque total
inicio = df_poblacion.index[df_poblacion["edad"] == "Todas las edades"][0]
fin = df_poblacion.index[df_poblacion["edad"] == "Hombres"][0]

df_total = df_poblacion.loc[inicio:fin - 1].copy()

# decada
df_poblacion.columns = df_poblacion.columns.astype(str)

columnas = ["edad"] + [str(año) for año in range(2026, 2037)]

df_total = df_total[columnas]

display(df_total.head())

,edad,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036
1,Todas las edades,49590099.0,5.007877e+07,5.055393e+07,5.100118e+07,5.141203e+07,5.178245e+07,5.211205e+07,5.240291e+07,5.265876e+07,5.288414e+07,5.308394e+07
2,0 años,323425.0,3.255249e+05,3.297576e+05,3.342223e+05,3.387731e+05,3.433373e+05,3.478817e+05,3.524054e+05,3.569122e+05,3.613875e+05,3.657939e+05
3,1 año,324651.0,3.316380e+05,3.335851e+05,3.374931e+05,3.415435e+05,3.456374e+05,3.497394e+05,3.538438e+05,3.579681e+05,3.621268e+05,3.663093e+05
4,2 años,330814.0,3.329214e+05,3.395938e+05,3.412688e+05,3.447869e+05,3.484016e+05,3.520507e+05,3.557263e+05,3.594418e+05,3.632257e+05,3.670972e+05
5,3 años,350186.0,3.387151e+05,3.406227e+05,3.468626e+05,3.482119e+05,3.513316e+05,3.545363e+05,3.577899e+05,3.611029e+05,3.644998e+05,3.680141e+05

In [24]:
df_poblacion_edades = df_total.copy()

# Extraer edad numérica
df_poblacion_edades["edad_num"] = (
    df_poblacion_edades["edad"]
    .str.extract(r"(\d+)")
    .astype(float)
)

# Seleccionar población de 18 a 79 años
df_poblacion_edades = (
    df_poblacion_edades.loc[
        df_poblacion_edades["edad_num"]
        .between(18, 79)
    ]
    .copy()
)

df_poblacion_edades["edad_num"] = (
    df_poblacion_edades["edad_num"].astype(int)
)

# Años que queremos analizar
años = [str(año) for año in range(2026, 2037)]

# Crear una nueva tabla en formato largo
df_poblacion_larga = df_poblacion_edades.melt(
    id_vars=["edad_num"],
    value_vars=años,
    var_name="periodo",
    value_name="poblacion"
)

# Convertir tipos
df_poblacion_larga["periodo"] = (
    df_poblacion_larga["periodo"].astype(int)
)

df_poblacion_larga["poblacion"] = pd.to_numeric(
    df_poblacion_larga["poblacion"],
    errors="coerce"
)

# Ordenar
df_poblacion_larga = (
    df_poblacion_larga
    .sort_values(["periodo", "edad_num"])
    .reset_index(drop=True)
)

display(df_poblacion_larga.head())

   edad_num  periodo  poblacion
0        18     2026   551342.0
1        19     2026   559068.0
2        20     2026   553819.0
3        21     2026   557615.0
4        22     2026   557311.0

In [25]:
print("Dimensiones:", df_poblacion_larga.shape)
print("Edad mínima:", df_poblacion_larga["edad_num"].min())
print("Edad máxima:", df_poblacion_larga["edad_num"].max())
print("Periodo mínimo:", df_poblacion_larga["periodo"].min())
print("Periodo máximo:", df_poblacion_larga["periodo"].max())

Dimensiones: (682, 3)
Edad mínima: 18
Edad máxima: 79
Periodo mínimo: 2026
Periodo máximo: 2036