#### Importación de bibliotecas

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Carga del dataset

In [ ]:
file = r"C:\Users\Evelyn\Documents\Evelyn\Learning\BCN Activa\simulador empresarial\ProjecteData\Equip_E\Data\alojamientos-turisticos-sample.csv"

df = pd.read_csv(file)
pd.set_option('display.max_columns', None) # ver todas las columnas
df.head()

,apartment_id,md5,name,description,host_id,neighborhood_overview,neighbourhood_name,neighbourhood_district,latitude,longitude,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,is_instant_bookable,reviews_per_month,country,city,insert_date
0,36187629,66fff4225feb2ddf104ea38f76e4bff1,Piso reformado excelente ubicacion,Apartamento reformado hace dos meses en el Cab...,261787331,NaN,BETERO,POBLATS MARITIMS,39.471490,-0.334600,Entire home/apt,4,2.0,3.0,3.0,"{TV,Wifi,""Air conditioning"",Kitchen,""Smoking a...",90.0,5,20,True,0,4,34,34,1,2019-08-19,2019-08-19,100.0,10.0,10.0,10.0,10.0,10.0,10.0,NaN,True,0.22,spain,valencia,2019-12-31
1,5388904,48790b4dd865e98cc1f5302a2bba1a50,Nice Room in a Penthouse,The apartment is fully equipped. Large bathroo...,20843074,NaN,la Nova Esquerra de l'Eixample,Eixample,41.383530,2.153880,Private room,1,1.0,1.0,1.0,"[""Wifi"", ""Kitchen"", ""Heating"", ""TV"", ""Essentia...",100.0,1,1125,True,0,0,0,0,1,2015-03-06,2015-03-06,80.0,8.0,8.0,8.0,10.0,10.0,10.0,NaN,False,0.01,spain,barcelona,2021-01-12
2,39982406,d3a60e8898bd8ddce4325c8d3d6af7c8,LUXURY 5 BEDROOM APARTMENT IN MONCLOA-ARAVACA,Luxury Apartment located in a priveleged zone ...,308267305,Very quiet residential area in a Posh area of ...,El Plantío,Moncloa - Aravaca,40.466140,-3.809480,Entire home/apt,10,3.0,5.0,8.0,"{TV,""Cable TV"",Wifi,""Air conditioning"",Pool,Ki...",220.0,1,30,True,30,60,90,365,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VT-12318,True,NaN,spain,madrid,2020-01-10
3,19344018,e2f33bae8c814924e8ce7e6efa8e7245,Habitación zona Atocha,Pareja joven alquila habitación para semana de...,135531703,NaN,Palos de Moguer,Arganzuela,40.405070,-3.693183,Private room,2,1.0,1.0,2.0,"{TV,Wifi,""Wheelchair accessible"",Kitchen,""Smok...",200.0,1,10,True,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,spain,madrid,2019-01-14
4,17218380,11295740bea58c9ae080a459cc8094c5,Spacious villa for rent with private pool,This large holiday home is located in a quiet ...,8345284,L'Escala has a strategic location - everything...,L'Escala,NaN,42.107823,3.141601,Entire home/apt,10,4.0,5.0,8.0,"{TV,Wifi,Pool,Kitchen,""Free parking on premise...",143.0,1,1125,True,27,43,56,56,5,2017-05-28,2018-08-11,84.0,9.0,8.0,8.0,9.0,8.0,8.0,HUTG-020958,True,0.29,spain,girona,2018-10-20

#### Exploración inicial

##### Tamaño

In [ ]:
df.shape

(10000, 40)

##### Tipos de datos

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   apartment_id                 10000 non-null  int64
 1   md5                          10000 non-null  object
 2   name                         9997 non-null   object
 3   description                  9862 non-null   object
 4   host_id                      10000 non-null  int64
 5   neighborhood_overview        5899 non-null   object
 6   neighbourhood_name           10000 non-null  object
 7   neighbourhood_district       6079 non-null   object
 8   latitude                     10000 non-null  float64
 9   longitude                    10000 non-null  float64
 10  room_type                    10000 non-null  object
 11  accommodates                 10000 non-null  int64
 12  bathrooms                    9926 non-null   float64
 13  bedrooms                     9930 non-null   float64
 14  beds                         9955 non-null   float64
 15  amenities_list               10000 non-null  object
 16  price                        9746 non-null   float64
 17  minimum_nights               10000 non-null  int64
 18  maximum_nights               10000 non-null  int64
 19  has_availability             9450 non-null   object
 20  availability_30              10000 non-null  int64
 21  availability_60              10000 non-null  int64
 22  availability_90              10000 non-null  int64
 23  availability_365             10000 non-null  int64
 24  number_of_reviews            10000 non-null  int64
 25  first_review_date            7396 non-null   object
 26  last_review_date             7395 non-null   object
 27  review_scores_rating         7291 non-null   float64
 28  review_scores_accuracy       7282 non-null   float64
 29  review_scores_cleanliness    7288 non-null   float64
 30  review_scores_checkin        7277 non-null   float64
 31  review_scores_communication  7286 non-null   float64
 32  review_scores_location       7276 non-null   float64
 33  review_scores_value          7276 non-null   float64
 34  license                      5144 non-null   object
 35  is_instant_bookable          10000 non-null  bool
 36  reviews_per_month            7396 non-null   float64
 37  country                      10000 non-null  object
 38  city                         10000 non-null  object
 39  insert_date                  10000 non-null  object
dtypes: bool(1), float64(14), int64(10), object(15)
memory usage: 3.0+ MB

##### Valores nulos

In [ ]:
df.isnull().sum()

apartment_id                      0
md5                               0
name                              3
description                     138
host_id                           0
neighborhood_overview          4101
neighbourhood_name                0
neighbourhood_district         3921
latitude                          0
longitude                         0
room_type                         0
accommodates                      0
bathrooms                        74
bedrooms                         70
beds                             45
amenities_list                    0
price                           254
minimum_nights                    0
maximum_nights                    0
has_availability                550
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
first_review_date              2604
last_review_date               2605
review_scores_rating           2709
review_scores_accuracy         2718
review_scores_cleanliness      2712
review_scores_checkin          2723
review_scores_communication    2714
review_scores_location         2724
review_scores_value            2724
license                        4856
is_instant_bookable               0
reviews_per_month              2604
country                           0
city                              0
insert_date                       0
dtype: int64

##### Duplicados

In [ ]:
df.duplicated().sum()

np.int64(0)

##### Exploración de outliers

In [ ]:
pd.set_option('display.max_columns', None)
df.describe()

# para ver en una primera instancia si hay outliers, por ejemplo en number_of_reviews hay una media de 26, pero el máximo es 588

,apartment_id,host_id,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000,9926.000000,9930.000000,9955.000000,9746.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,7291.000000,7282.000000,7288.000000,7277.000000,7286.000000,7276.000000,7276.000000,7396.000000
mean,2.115440e+07,9.058066e+07,40.400758,0.277637,4.272300,1.595910,1.937059,2.923456,101.211090,4.953000,759.771900,13.01330,28.759300,46.106800,187.938800,26.020600,91.929776,9.450151,9.315587,9.623883,9.622152,9.544942,9.137713,1.431202
std,1.157967e+07,8.695851e+07,1.417085,3.224372,2.582716,0.990137,1.370144,2.261214,86.099548,17.728763,498.367763,11.83514,22.972034,33.745279,130.777964,52.347588,9.226981,0.946763,1.006235,0.826610,0.827528,0.767761,0.996765,1.588320
min,1.196400e+04,1.070400e+04,36.651664,-6.026849,1.000000,0.000000,0.000000,0.000000,6.000000,1.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.010000
25%,1.328672e+07,1.488728e+07,39.705929,-3.696577,2.000000,1.000000,1.000000,1.000000,45.000000,1.000000,62.000000,0.00000,2.000000,10.000000,66.000000,0.000000,89.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.270000
50%,2.059847e+07,6.533700e+07,40.426165,2.164050,4.000000,1.000000,2.000000,2.000000,75.000000,2.000000,1125.000000,11.00000,29.000000,49.000000,183.000000,5.000000,94.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.000000,0.840000
75%,2.995999e+07,1.428246e+08,41.397804,2.892970,6.000000,2.000000,3.000000,4.000000,124.000000,4.000000,1125.000000,26.00000,53.000000,80.000000,318.000000,27.000000,98.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.060000
max,4.806155e+07,3.874783e+08,42.461280,4.301780,29.000000,13.000000,50.000000,30.000000,500.000000,1125.000000,1125.000000,30.00000,60.000000,90.000000,365.000000,588.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,12.910000