In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import mysql.connector

In [4]:
import mysql.connector

conexion = mysql.connector.connect(
    host="212.227.148.202",
    port=3306,
    user="Equipo34",
    password="E1q2u3i4p5o34",
    database="Equip_34"
)

import pandas as pd

df = pd.read_sql(
    "SELECT * FROM Tourist_Accommodation;",
    conexion
)

C:\Users\lacal\AppData\Local\Temp\ipykernel_29500\3372738357.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

In [5]:
# tamaño de la DB

df.shape

(7001, 35)

hay 7001 filas y 35 columnas

In [6]:
#informacion general, tipo de variable
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7001 entries, 0 to 7000
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   apartment_id                 7001 non-null   int64
 1   name                         6998 non-null   object
 2   description                  6972 non-null   object
 3   host_id                      7001 non-null   int64
 4   neighbourhood_name           7001 non-null   object
 5   neighbourhood_district       4241 non-null   object
 6   room_type                    7001 non-null   object
 7   accommodates                 7001 non-null   int64
 8   bathrooms                    6969 non-null   object
 9   bedrooms                     6972 non-null   object
 10  beds                         6998 non-null   float64
 11  amenities_list               6984 non-null   object
 12  price                        6870 non-null   float64
 13  minimum_nights               7001 non-null   int64
 14  maximum_nights               7001 non-null   int64
 15  has_availability             6451 non-null   object
 16  availability_30              7001 non-null   int64
 17  availability_60              7001 non-null   int64
 18  availability_90              7001 non-null   int64
 19  availability_365             7001 non-null   int64
 20  number_of_reviews            7001 non-null   int64
 21  first_review_date            5747 non-null   object
 22  last_review_date             5746 non-null   object
 23  review_scores_rating         5674 non-null   float64
 24  review_scores_accuracy       5665 non-null   float64
 25  review_scores_cleanliness    5671 non-null   float64
 26  review_scores_checkin        5660 non-null   float64
 27  review_scores_communication  5669 non-null   float64
 28  review_scores_location       5659 non-null   float64
 29  review_scores_value          5659 non-null   float64
 30  is_instant_bookable          7001 non-null   object
 31  reviews_per_month            5747 non-null   float64
 32  country                      7001 non-null   object
 33  city                         7001 non-null   object
 34  insert_date                  7001 non-null   object
dtypes: float64(10), int64(10), object(15)
memory usage: 1.9+ MB

In [ ]:
#estadisticos variables numericas

df.describe().round(2)

,apartment_id,host_id,accommodates,beds,price,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,7001.00,7.001000e+03,7001.00,6998.00,6870.00,7001.00,7001.00,7001.00,7001.00,7001.00,7001.00,7001.00,5674.00,5665.00,5671.0,5660.00,5669.00,5659.00,5659.00,5747.00
mean,15119780.99,6.218673e+07,4.35,3.01,1011.10,4.42,759.47,12.28,27.42,44.31,188.13,34.13,920.23,94.54,93.2,96.29,96.43,95.31,91.46,123.04
std,7715577.75,5.747094e+07,2.62,2.33,845.98,10.67,497.96,11.51,22.41,33.02,129.96,59.94,85.35,9.06,9.7,7.96,7.61,7.30,9.31,153.16
min,11964.00,1.070400e+04,1.00,0.00,60.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,200.00,20.00,20.0,20.00,20.00,20.00,20.00,1.00
25%,8749646.00,1.050015e+07,2.00,1.00,450.00,1.00,70.00,0.00,2.00,9.00,66.00,1.00,890.00,90.00,90.0,90.00,90.00,90.00,90.00,17.00
50%,16737061.00,4.261380e+07,4.00,2.00,750.00,2.00,1125.00,10.00,26.00,46.00,190.00,9.00,940.00,100.00,100.0,100.00,100.00,100.00,90.00,57.00
75%,21463214.00,1.062896e+08,6.00,4.00,1230.00,4.00,1125.00,24.00,50.00,76.00,316.00,40.00,980.00,100.00,100.0,100.00,100.00,100.00,100.00,177.00
max,27245117.00,3.365242e+08,29.00,30.00,6071.00,365.00,1125.00,30.00,60.00,90.00,365.00,588.00,1000.00,100.00,100.0,100.00,100.00,100.00,100.00,1291.00

In [17]:
#estadisticos variables categoricas
df.describe(include="object")

,name,description,neighbourhood_name,neighbourhood_district,room_type,bathrooms,bedrooms,amenities_list,has_availability,first_review_date,last_review_date,is_instant_bookable,country,city,insert_date
count,6998,6972,7001,4241,7001,6969,6972,6984,6451,5747,5746,7001,7001,7001,7001
unique,6755,6790,478,61,4,13,14,6792,1,1793,1459,2,1,8,164
top,Beautiful two bedroom appartment with comunita...,This apartment is part of a nice and well kept...,la Dreta de l'Eixample,Eixample,Entire home/apt,1,1,"TV,Wifi,Air conditioning,Kitchen,Elevator,Heat...",VERDADERO,01/04/2018,08/03/2020,VERDADERO,spain,barcelona,14/05/2018
freq,4,4,262,786,4979,4144,3141,9,6451,27,28,3740,7001,2127,136

In [ ]:
# VALORES NULOS

nulos = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "%": (df.isnull().mean() * 100).round(2)
})

nulos = nulos[nulos["Nulos"] > 0]

nulos = nulos.sort_values("%", ascending=False)

print(nulos)

                             Nulos      %
neighbourhood_district        2760  39.42
review_scores_value           1342  19.17
review_scores_location        1342  19.17
review_scores_checkin         1341  19.15
review_scores_accuracy        1336  19.08
review_scores_communication   1332  19.03
review_scores_cleanliness     1330  19.00
review_scores_rating          1327  18.95
last_review_date              1255  17.93
first_review_date             1254  17.91
reviews_per_month             1254  17.91
has_availability               550   7.86
price                          131   1.87
bathrooms                       32   0.46
description                     29   0.41
bedrooms                        29   0.41
amenities_list                  17   0.24
name                             3   0.04
beds                             3   0.04

Hay nulos principalmente en neighbourhood_district y review_scores.

In [10]:
# duplicados

df.duplicated().sum()

np.int64(0)

No existen registros duplicados.

In [ ]:
# tipos de variables numericas
df.select_dtypes(include="number").columns

Index(['apartment_id', 'host_id', 'accommodates', 'beds', 'price',
       'minimum_nights', 'maximum_nights', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'reviews_per_month'],
      dtype='object')

In [ ]:
# tipo de variables numericas 
df.select_dtypes(include="object").columns

In [25]:
# Variables categóricas
categoricas = [
    "room_type",
    "city",
    "country",
    "has_availability"
]

for col in categoricas:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- room_type ---
room_type
Entire home/apt    4979
Private room       1942
Shared room          45
Hotel room           35
Name: count, dtype: int64

--- city ---
city
barcelona    2127
madrid       1446
mallorca     1144
girona       1125
sevilla       361
malaga        350
valencia      307
menorca       141
Name: count, dtype: int64

--- country ---
country
spain    7001
Name: count, dtype: int64

--- has_availability ---
has_availability
VERDADERO    6451
None          550
Name: count, dtype: int64