In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import mysql.connector

In [7]:
import mysql.connector

conexion = mysql.connector.connect(
    host="212.227.148.202",
    port=3306,
    user="Equipo34",
    password="E1q2u3i4p5o34",
    database="Equip_34"
)

import pandas as pd

df = pd.read_sql(
    "SELECT * FROM Tourist_Accommodation;",
    conexion
)

df.head()

C:\Users\lacal\AppData\Local\Temp\ipykernel_27368\3076837788.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date
0,11964,A ROOM WITH A VIEW,Private bedroom in our attic apartment. Right ...,45553,Centro,None,Private room,2,2,1,...,100.0,100.0,100.0,100.0,100.0,FALSO,75.0,spain,malaga,31/07/2018
1,21853,Bright and airy room,We have a quiet and sunny room with a good vie...,83531,C�rmenes,Latina,Private room,1,1,1,...,90.0,100.0,100.0,80.0,90.0,FALSO,52.0,spain,madrid,10/01/2020
2,32347,Explore Cultural Sights from a Family-Friendly...,Open French doors and step onto a plant-filled...,139939,San Vicente,Casco Antiguo,Entire home/apt,4,1,2,...,100.0,100.0,100.0,100.0,100.0,VERDADERO,142.0,spain,sevilla,29/07/2019
3,35379,Double 02 CasanovaRooms Barcelona,Room at a my apartment. Kitchen and 2 bathroom...,152232,l'Antiga Esquerra de l'Eixample,Eixample,Private room,2,2,1,...,90.0,100.0,100.0,100.0,90.0,VERDADERO,306.0,spain,barcelona,10/01/2020
4,35801,Can Torras Farmhouse Studio Suite,Lay in bed & watch sunlight change the mood of...,153805,Quart,None,Private room,5,1,2,...,100.0,100.0,100.0,100.0,100.0,FALSO,39.0,spain,girona,19/02/2019

In [10]:
df.describe()

,apartment_id,host_id,accommodates,beds,price,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,7.001000e+03,7.001000e+03,7001.000000,6998.000000,6870.000000,7001.000000,7001.000000,7001.000000,7001.000000,7001.000000,7001.00000,7001.000000,5674.000000,5665.000000,5671.000000,5660.000000,5669.000000,5659.000000,5659.000000,5747.000000
mean,1.511978e+07,6.218673e+07,4.351807,3.013575,1011.098108,4.424939,759.467647,12.277389,27.419940,44.306670,188.12941,34.125411,920.232640,94.543689,93.196967,96.287986,96.434997,95.311893,91.459622,123.041239
std,7.715578e+06,5.747094e+07,2.620646,2.330849,845.975377,10.669575,497.964843,11.510798,22.413425,33.017183,129.95633,59.935608,85.353954,9.063156,9.702261,7.963854,7.605426,7.295274,9.309337,153.161803
min,1.196400e+04,1.070400e+04,1.000000,0.000000,60.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,200.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,1.000000
25%,8.749646e+06,1.050015e+07,2.000000,1.000000,450.000000,1.000000,70.000000,0.000000,2.000000,9.000000,66.00000,1.000000,890.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,17.000000
50%,1.673706e+07,4.261380e+07,4.000000,2.000000,750.000000,2.000000,1125.000000,10.000000,26.000000,46.000000,190.00000,9.000000,940.000000,100.000000,100.000000,100.000000,100.000000,100.000000,90.000000,57.000000
75%,2.146321e+07,1.062896e+08,6.000000,4.000000,1230.000000,4.000000,1125.000000,24.000000,50.000000,76.000000,316.00000,40.000000,980.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,177.000000
max,2.724512e+07,3.365242e+08,29.000000,30.000000,6071.000000,365.000000,1125.000000,30.000000,60.000000,90.000000,365.00000,588.000000,1000.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,1291.000000

TypeError: 'Index' object is not callable