In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Portátil\Desktop\Work\Simulacio_empr\Sprint4\02_Datos procesados (2)\02_Productos_Activos_2021_GEN.csv",sep=";")
df.head()

,a01: anio de la entrevista,"b0100: poseen cuentas corrientes, libretas u otros depositos...?",b0110a,b0110b,b0110c,b0110d,b0110e,b0110f,b0110g,b0120a,...,b0720i,b0710a,b0710b,b0710c,b0710d,b0710e,b0710f,b0710g,b0710h,b0710i
0,2022,1,0,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,2022,1,1,1,1,1,1,0,0,1,...,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98
2,2022,1,0,1,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,2022,1,0,1,0,1,1,0,0,0,...,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98
4,2022,1,1,1,1,0,1,0,0,1,...,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98

In [5]:
#Eliminar text deixar nomes codi
df.columns = df.columns.str.split(':').str[0]
df.head(2)

,a01,b0100,b0110a,b0110b,b0110c,b0110d,b0110e,b0110f,b0110g,b0120a,...,b0720i,b0710a,b0710b,b0710c,b0710d,b0710e,b0710f,b0710g,b0710h,b0710i
0,2022,1,0,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,2022,1,1,1,1,1,1,0,0,1,...,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98

In [6]:
cols_to_drop = [
    # b0110
    'b0110a','b0110b','b0110c','b0110d','b0110e','b0110f','b0110g',
    'b0120a','b0120b','b0120c','b0120d','b0120e','b0120f','b0130a','b0130b','b0130c',
    # b0200 bloc
    'b0201','b0202','b0203','b0204','b0205','b0206','b0207',
    'b0208','b0209','b0210','b0212',
    'b0312','b0412','b0503','b0710a','b0710b','b0710c','b0710d','b0710e','b0710f','b0710g','b0710h','b0710i',
    # b0720
    'b0720a','b0720b','b0720c','b0720d','b0720e','b0720f','b0720g','b0720h','b0720i'
]

df = df.drop(columns=cols_to_drop, errors='ignore')

### Convertir columnas: texto , valores

In [7]:
#codigos estraños
nonresponse = [-3, -4, -5, -96, -97, -98, -99]

In [8]:
# convertimos variables en texto
mapping_text = {
    'b0302': 'Plan pensiones',
    'b0303': 'Fondo inver.',
    'b0304': 'Acciones',
    'b0305': 'Activo renta fija',
    'b0308': 'Cuenta o depósito ahorro',
    'b0301': 'Hipoteca',
    'b0306': 'Ptmo personal',
    'b0307': 'Tjta credito',
    'b0309': 'Seg. vida',
    'b0310': 'Seg. médico'
}

for col, text in mapping_text.items():
    df[text] = df[col].apply(
        lambda x: (
            "Sí" if x == 1 else
            "No" if x == 0 else
            x  # deixa el codi tal qual (-3, -4, -5, -96, -97, -98, -99)
        )
    )

In [9]:
#convertimos codigos negativos
# diccionario de códigos negativos ECF
nonresponse_text = {
    -3:  "No sabe leer",
    -4:  "Valor no fiable",
    -5:  "Error CAPI/entrevistador",
    -96: "NS/NC",
    -97: "No sabe",
    -98: "N/A",
    -99: "No contesta"
}

# aplicamos la conversión SOLO a las columnas nuevas creadas
for text in mapping_text.values():
    df[text] = df[text].replace(nonresponse_text)

In [10]:
df=df.drop(columns=['b0301','b0302','b0303','b0304','b0305','b0306','b0307','b0308','b0309','b0310'])

In [11]:
# convertimos variables en texto
mapping_text2 = {
    'b0402': 'Plan pensiones (L2Y)',
    'b0403': 'Fondo inver.(L2Y)',
    'b0404': 'Acciones (L2Y)',
    'b0405': 'Activo renta fija (L2Y)',
    'b0408': 'Cta o depósito ahorro (L2Y)',
    'b0401': 'Hipoteca (L2Y)',
    'b0406': 'Ptmo personal (L2Y)',
    'b0407': 'Tjta credito (L2Y)',
    'b0409': 'Seg. vida (L2Y)',
    'b0410': 'Seg. médico (L2Y)',
    'b0100': 'Tienen Product fin.'
}

for col, text in mapping_text2.items():
    df[text] = df[col].apply(
        lambda x: (
            "Sí" if x == 1 else
            "No" if x == 0 else
            x  # deixa el codi tal qual (-3, -4, -5, -96, -97, -98, -99)
        )
    )

In [12]:
#convertimos codigos negativos
# diccionario de códigos negativos ECF
nonresponse_text = {
    -3:  "No sabe leer",
    -4:  "Valor no fiable",
    -5:  "Error CAPI/entrevistador",
    -96: "NS/NC",
    -97: "No sabe",
    -98: "N/A",
    -99: "No contesta"
}

# aplicamos la conversión SOLO a las columnas nuevas creadas
for text in mapping_text2.values():
    df[text] = df[text].replace(nonresponse_text)

In [13]:
df=df.drop(columns=['b0401','b0402','b0403','b0404','b0405','b0406','b0407','b0408','b0409','b0410','b0600'])

In [14]:
b0502_map = {
    1: "Cuenta corriente",
    2: "Cuenta ahorro",
    3: "Depósito a plazo",
    4: "Fondo inver.",
    5: "Acciones",
    6: "Hipoteca",
    7: "Ptmo personal",
    8: "Tjta de crédito",
    9: "Seg. vida",
    10: "Seg. médico",
    11: "Plan pensiones",
    12: "Otros productos",
    -98: "N/A (filtro)",
    -97: "No sabe",
    -99: "No contesta",
    -5: "Error CAPI"
}

df["Último producto contratado"] = df["b0502"].replace(b0502_map)

In [15]:
df = df.rename(columns={
        'a01': 'Año_entrev.'  })

In [16]:
df=df.drop(columns=['b0502','b0100'])

In [17]:
df.head(10)

,Año_entrev.,Plan pensiones,Fondo inver.,Acciones,Activo renta fija,Cuenta o depósito ahorro,Hipoteca,Ptmo personal,Tjta credito,Seg. vida,...,Acciones (L2Y),Activo renta fija (L2Y),Cta o depósito ahorro (L2Y),Hipoteca (L2Y),Ptmo personal (L2Y),Tjta credito (L2Y),Seg. vida (L2Y),Seg. médico (L2Y),Tienen Product fin.,Último producto contratado
0,2022,No,No,No,No,No,Sí,Sí,Sí,No,...,No,No,No,No,Sí,No,No,No,Sí,Hipoteca
1,2022,No,No,No,No,No,No,Sí,Sí,No,...,No,No,No,No,No,No,No,No,Sí,N/A (filtro)
2,2022,Sí,Sí,Sí,No,No,No,No,Sí,No,...,Sí,Sí,No,No,No,Sí,No,No,Sí,Fondo inver.
3,2022,Sí,No,No,No,Sí,Sí,No,Sí,Sí,...,No,No,No,No,No,No,No,No,Sí,N/A (filtro)
4,2022,No,No,No,No,N/A,No,Sí,Sí,No,...,No,No,N/A,No,Sí,No,No,No,Sí,Error CAPI
5,2022,No,No,No,No,N/A,No,No,No,No,...,No,No,N/A,No,No,No,No,No,Sí,N/A (filtro)
6,2022,Sí,Sí,No,No,Sí,Sí,Sí,Sí,Sí,...,No,No,Sí,No,No,No,No,No,Sí,Depósito a plazo
7,2022,N/A,N/A,N/A,N/A,N/A,No,No,No,No,...,N/A,N/A,N/A,No,No,No,No,No,No,N/A (filtro)
8,2022,Sí,Sí,N/A,No,N/A,No,No,Sí,No,...,N/A,No,N/A,No,No,No,No,No,Sí,Depósito a plazo
9,2022,No,No,No,No,No,Sí,No,Sí,No sabe,...,No,No,No,No,No,No,No,Sí,Sí,Seg. médico

In [18]:
df.to_csv("C:/Users/Portátil/ProjecteData/Equip_23/Data/8 April/02_Product_Activos_cleaning_21.csv",index=False)