In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Portátil\Desktop\Work\Simulacio_empr\Sprint4\Origin_data\2016\ecf_2016.csv (1)\ecf_2016.csv",sep=";")
df.head()

,a01,a02,a0000,a0100,a0400,a04,a0800,a0900a,a0900b,a0900c,...,ccaaf,age,j0300p,j0800h,a0300,ID,a1800,g0800,a0200,weight
0,2016,12,0,1,1998,18,-98,0,0,0,...,1,18,-98,-98,-98,1114,-98,-98,1,5446.342386
1,2016,10,0,1,1982,33,-98,0,1,1,...,1,33,-98,0,-98,1136,45,-98,1,6316.522504
2,2016,10,1,1,1967,49,-98,0,1,1,...,1,49,-98,0,-98,3783,63,-98,1,6204.820715
3,2016,10,0,1,1962,54,-98,0,1,0,...,1,54,-98,-98,-98,171,95,-98,1,4990.569326
4,2016,10,0,1,1952,64,-98,0,1,0,...,1,64,-98,-98,-98,2945,77,-98,1,6204.776338

In [3]:
print(df.columns.to_list())

['a01', 'a02', 'a0000', 'a0100', 'a0400', 'a04', 'a0800', 'a0900a', 'a0900b', 'a0900c', 'a0900d', 'a0900e', 'a0900f', 'a0900g', 'a0900h', 'a0900i', 'a0900j', 'a0900k', 'a1000', 'a1100', 'a1200', 'a1300', 'a1400', 'a1500', 'a1600', 'a1700', 'a1900', 'a2000', 'a2100', 'a2200', 'a2300', 'a2400', 'b0100', 'b0208', 'b0308', 'b0408', 'b0201', 'b0301', 'b0401', 'b0202', 'b0302', 'b0402', 'b0203', 'b0303', 'b0403', 'b0204', 'b0304', 'b0404', 'b0205', 'b0305', 'b0405', 'b0206', 'b0306', 'b0406', 'b0207', 'b0307', 'b0407', 'b0209', 'b0309', 'b0409', 'b0210', 'b0310', 'b0410', 'b0502', 'b0600', 'b0700a', 'b0700b', 'b0700c', 'b0700d', 'b0700e', 'b0700f', 'b0700g', 'b0700h', 'b0700i', 'b0700j', 'b0700k', 'b0700l', 'b0700m', 'b0700n', 'b0700o', 'b0700p', 'b0700q', 'b0700r', 'b0700s', 'b0700t', 'b0800', 'b0901', 'b0902', 'b0903', 'b0904', 'b1000a', 'b1000b', 'b1000c', 'b1000d', 'b1000e', 'b1000f', 'b1000g', 'b1000h', 'b1000i', 'b1000j', 'b1101', 'b1102', 'b1103', 'b1201', 'b1202a', 'b1202b', 'b1202c', 'b1202d', 'b1202e', 'b1202f', 'b1202g', 'b1202h', 'b1202i', 'b1202j', 'b1202k', 'b1202l', 'b1202m', 'b1202n', 'c0100', 'c0200a', 'c0200b', 'c0200c', 'c0200d', 'c0200e', 'c0200f', 'c0200g', 'c0200h', 'c0200i', 'c0200j', 'c0300', 'c0400a', 'c0400b', 'c0400c', 'c0400d', 'c0400e', 'c0400f', 'c0400g', 'c0400h', 'c0400i', 'c0400j', 'c0400k', 'c0400l', 'c0400m', 'c0400n', 'c0500', 'c0600a', 'c0600b', 'c0600c', 'c0600d', 'c0600e', 'c0600f', 'c0600g', 'c0600h', 'c0600i', 'c0600j', 'c0600k', 'd0101', 'd0102', 'd0103', 'd0104', 'd0105', 'd0106', 'd0107', 'd0108', 'd0109', 'd0110', 'd0111', 'd0112', 'd0200', 'd0300', 'd0400', 'd0500', 'd0600', 'e0100', 'e0500', 'e0600', 'e0700', 'e0800', 'e0900', 'e1001', 'e1002', 'e1003', 'e1101', 'e1102', 'e1200', 'e0200a', 'e0200b', 'e0200c', 'e0200d', 'e0200e', 'e0401', 'tmp_e0401', 'e0402', 'e0403', 'e0300', 'f0100', 'f0200', 'f0300', 'f0400', 'f0600', 'f0700', 'f0800', 'g0000', 'g0100', 'a05', 'g0500', 'g0600', 'g0700', 'g0900', 'g1008', 'g1108', 'g1208', 'g1001', 'g1101', 'g1201', 'g1002', 'g1102', 'g1202', 'g1003', 'g1103', 'g1203', 'g1004', 'g1104', 'g1204', 'g1005', 'g1105', 'g1205', 'g1006', 'g1106', 'g1206', 'g1007', 'g1107', 'g1207', 'g1009', 'g1109', 'g1209', 'g1010', 'g1110', 'g1210', 'g1302', 'g1400', 'g1500a', 'g1500b', 'g1500c', 'g1500d', 'g1500e', 'g1500f', 'g1500g', 'g1500h', 'g1500i', 'g1500j', 'g1500k', 'g1500l', 'g1500m', 'g1500n', 'g1500o', 'g1500p', 'g1500q', 'g1500r', 'g1500s', 'g1500t', 'g1600', 'g1701', 'g1702', 'g1703', 'g1704', 'g1800a', 'g1800b', 'g1800c', 'g1800d', 'g1800e', 'g1800f', 'g1800g', 'g1800h', 'g1800i', 'g1800j', 'h0100', 'h0500', 'h0600', 'h0700', 'h0800', 'h0900', 'h1001', 'h1002', 'h1003', 'h1101', 'h1102', 'h1200', 'h0200a', 'h0200b', 'h0200c', 'h0200d', 'h0200e', 'h0401', 'tmp_h0401', 'h0402', 'h0403', 'h0300', 'i0100', 'i0200a', 'i0200b', 'i0200c', 'i0200d', 'i0200e', 'i0200f', 'i0200g', 'i0200h', 'i0300', 'i0400a', 'i0400b', 'i0400c', 'i0400d', 'i0400e', 'i0500a', 'i0500b', 'i0500c', 'i0500d', 'i0500e', 'i0500f', 'i0500g', 'i0500h', 'i0500i', 'i0500j', 'i0601', 'i0602', 'i0700', 'i0800', 'i0900', 'i1000', 'j0100', 'j0200', 'j0300a', 'j0300b', 'j0300c', 'j0300d', 'j0300e', 'j0300f', 'j0300g', 'j0300h', 'j0300i', 'j0300j', 'j0300k', 'j0300l', 'j0300m', 'j0300n', 'j0300o', 'j0400', 'j0500', 'j0600', 'j0700', 'j0800a', 'j0800b', 'j0800c', 'j0800d', 'j0800e', 'j0800f', 'j0800g', 'j0900a', 'j0900b', 'j0900c', 'j0900d', 'j1000', 'j1100', 'j1201', 'j1202', 'j1203', 'j1300', 'j1400', 'ccaaf', 'age', 'j0300p', 'j0800h', 'a0300', 'ID', 'a1800', 'g0800', 'a0200', 'weight']

In [4]:
cols_keep = [
    'id','age','a01','a0100','b0100','b0301','b0302','b0303','b0304','b0306','b0305',
    'b0307','b0308','b0309','b0310','b0401','b0402','b0403','b0404','b0406','b0405',
    'b0407','b0408','b0409','b0410','b0502'
]

cols_all = [
    'a01', 'a02', 'a0000', 'a0100', 'a0400', 'a04', 'a0800', 'a0900a', 'a0900b', 'a0900c',
    'a0900d', 'a0900e', 'a0900f', 'a0900g', 'a0900h', 'a0900i', 'a0900j', 'a0900k', 'a1000',
    'a1100', 'a1200', 'a1300', 'a1400', 'a1500', 'a1600', 'a1700', 'a1900', 'a2000', 'a2100',
    'a2200', 'a2300', 'a2400', 'b0100', 'b0208', 'b0308', 'b0408', 'b0201', 'b0301', 'b0401',
    'b0202', 'b0302', 'b0402', 'b0203', 'b0303', 'b0403', 'b0204', 'b0304', 'b0404', 'b0205',
    'b0305', 'b0405', 'b0206', 'b0306', 'b0406', 'b0207', 'b0307', 'b0407', 'b0209', 'b0309',
    'b0409', 'b0210', 'b0310', 'b0410', 'b0502', 'b0600', 'b0700a', 'b0700b', 'b0700c',
    'b0700d', 'b0700e', 'b0700f', 'b0700g', 'b0700h', 'b0700i', 'b0700j', 'b0700k', 'b0700l',
    'b0700m', 'b0700n', 'b0700o', 'b0700p', 'b0700q', 'b0700r', 'b0700s', 'b0700t', 'b0800',
    'b0901', 'b0902', 'b0903', 'b0904', 'b1000a', 'b1000b', 'b1000c', 'b1000d', 'b1000e',
    'b1000f', 'b1000g', 'b1000h', 'b1000i', 'b1000j', 'b1101', 'b1102', 'b1103', 'b1201',
    'b1202a', 'b1202b', 'b1202c', 'b1202d', 'b1202e', 'b1202f', 'b1202g', 'b1202h', 'b1202i',
    'b1202j', 'b1202k', 'b1202l', 'b1202m', 'b1202n', 'c0100', 'c0200a', 'c0200b', 'c0200c',
    'c0200d', 'c0200e', 'c0200f', 'c0200g', 'c0200h', 'c0200i', 'c0200j', 'c0300', 'c0400a',
    'c0400b', 'c0400c', 'c0400d', 'c0400e', 'c0400f', 'c0400g', 'c0400h', 'c0400i', 'c0400j',
    'c0400k', 'c0400l', 'c0400m', 'c0400n', 'c0500', 'c0600a', 'c0600b', 'c0600c', 'c0600d',
    'c0600e', 'c0600f', 'c0600g', 'c0600h', 'c0600i', 'c0600j', 'c0600k', 'd0101', 'd0102',
    'd0103', 'd0104', 'd0105', 'd0106', 'd0107', 'd0108', 'd0109', 'd0110', 'd0111', 'd0112',
    'd0200', 'd0300', 'd0400', 'd0500', 'd0600', 'e0100', 'e0500', 'e0600', 'e0700', 'e0800',
    'e0900', 'e1001', 'e1002', 'e1003', 'e1101', 'e1102', 'e1200', 'e0200a', 'e0200b',
    'e0200c', 'e0200d', 'e0200e', 'e0401', 'tmp_e0401', 'e0402', 'e0403', 'e0300', 'f0100',
    'f0200', 'f0300', 'f0400', 'f0600', 'f0700', 'f0800', 'g0000', 'g0100', 'a05', 'g0500',
    'g0600', 'g0700', 'g0900', 'g1008', 'g1108', 'g1208', 'g1001', 'g1101', 'g1201', 'g1002',
    'g1102', 'g1202', 'g1003', 'g1103', 'g1203', 'g1004', 'g1104', 'g1204', 'g1005', 'g1105',
    'g1205', 'g1006', 'g1106', 'g1206', 'g1007', 'g1107', 'g1207', 'g1009', 'g1109', 'g1209',
    'g1010', 'g1110', 'g1210', 'g1302', 'g1400', 'g1500a', 'g1500b', 'g1500c', 'g1500d',
    'g1500e', 'g1500f', 'g1500g', 'g1500h', 'g1500i', 'g1500j', 'g1500k', 'g1500l', 'g1500m',
    'g1500n', 'g1500o', 'g1500p', 'g1500q', 'g1500r', 'g1500s', 'g1500t', 'g1600', 'g1701',
    'g1702', 'g1703', 'g1704', 'g1800a', 'g1800b', 'g1800c', 'g1800d', 'g1800e', 'g1800f',
    'g1800g', 'g1800h', 'g1800i', 'g1800j', 'h0100', 'h0500', 'h0600', 'h0700', 'h0800',
    'h0900', 'h1001', 'h1002', 'h1003', 'h1101', 'h1102', 'h1200', 'h0200a', 'h0200b',
    'h0200c', 'h0200d', 'h0200e', 'h0401', 'tmp_h0401', 'h0402', 'h0403', 'h0300', 'i0100',
    'i0200a', 'i0200b', 'i0200c', 'i0200d', 'i0200e', 'i0200f', 'i0200g', 'i0200h', 'i0300',
    'i0400a', 'i0400b', 'i0400c', 'i0400d', 'i0400e', 'i0500a', 'i0500b', 'i0500c', 'i0500d',
    'i0500e', 'i0500f', 'i0500g', 'i0500h', 'i0500i', 'i0500j', 'i0601', 'i0602', 'i0700',
    'i0800', 'i0900', 'i1000', 'j0100', 'j0200', 'j0300a', 'j0300b', 'j0300c', 'j0300d',
    'j0300e', 'j0300f', 'j0300g', 'j0300h', 'j0300i', 'j0300j', 'j0300k', 'j0300l', 'j0300m',
    'j0300n', 'j0300o', 'j0400', 'j0500', 'j0600', 'j0700', 'j0800a', 'j0800b', 'j0800c',
    'j0800d', 'j0800e', 'j0800f', 'j0800g', 'j0900a', 'j0900b', 'j0900c', 'j0900d', 'j1000',
    'j1100', 'j1201', 'j1202', 'j1203', 'j1300', 'j1400', 'ccaaf', 'age', 'j0300p', 'j0800h',
    'a0300', 'ID', 'a1800', 'g0800', 'a0200', 'weight'
]

cols_drop = [c for c in cols_all if c not in cols_keep]

df = df.drop(columns=cols_drop)

### Convertir columnas: texto , valores

In [5]:
#codigos estraños
nonresponse = [-3, -4, -5, -96, -97, -98, -99]

In [6]:
# convertimos variables en texto
mapping_text = {
    'b0302': 'Plan pensiones',
    'b0303': 'Fondo inver.',
    'b0304': 'Acciones',
    'b0305': 'Activo renta fija',
    'b0308': 'Cuenta o depósito ahorro',
    'b0301': 'Hipoteca',
    'b0306': 'Ptmo personal',
    'b0307': 'Tjta credito',
    'b0309': 'Seg. vida',
    'b0310': 'Seg. médico'
}

for col, text in mapping_text.items():
    df[text] = df[col].apply(
        lambda x: (
            "Sí" if x == 1 else
            "No" if x == 0 else
            x  # deixa el codi tal qual (-3, -4, -5, -96, -97, -98, -99)
        )
    )

In [7]:
#convertimos codigos negativos
# diccionario de códigos negativos ECF
nonresponse_text = {
    -3:  "No sabe leer",
    -4:  "Valor no fiable",
    -5:  "Error CAPI/entrevistador",
    -96: "NS/NC",
    -97: "No sabe",
    -98: "N/A",
    -99: "No contesta"
}

# aplicamos la conversión SOLO a las columnas nuevas creadas
for text in mapping_text.values():
    df[text] = df[text].replace(nonresponse_text)

In [8]:
df=df.drop(columns=['b0301','b0302','b0303','b0304','b0305','b0306','b0307','b0308','b0309','b0310'])

In [9]:
# convertimos variables en texto
mapping_text2 = {
    'b0402': 'Plan pensiones (L2Y)',
    'b0403': 'Fondo inver.(L2Y)',
    'b0404': 'Acciones (L2Y)',
    'b0405': 'Activo renta fija (L2Y)',
    'b0408': 'Cta o depósito ahorro (L2Y)',
    'b0401': 'Hipoteca (L2Y)',
    'b0406': 'Ptmo personal (L2Y)',
    'b0407': 'Tjta credito (L2Y)',
    'b0409': 'Seg. vida (L2Y)',
    'b0410': 'Seg. médico (L2Y)',
    'b0100': 'Tienen Product fin.'
}

for col, text in mapping_text2.items():
    df[text] = df[col].apply(
        lambda x: (
            "Sí" if x == 1 else
            "No" if x == 0 else
            x  # deixa el codi tal qual (-3, -4, -5, -96, -97, -98, -99)
        )
    )

In [10]:
#convertimos codigos negativos
# diccionario de códigos negativos ECF
nonresponse_text = {
    -3:  "No sabe leer",
    -4:  "Valor no fiable",
    -5:  "Error CAPI/entrevistador",
    -96: "NS/NC",
    -97: "No sabe",
    -98: "N/A",
    -99: "No contesta"
}

# aplicamos la conversión SOLO a las columnas nuevas creadas
for text in mapping_text2.values():
    df[text] = df[text].replace(nonresponse_text)

In [11]:
df=df.drop(columns=['b0401','b0402','b0403','b0404','b0405','b0406','b0407','b0408','b0409','b0410','b0100'])

In [12]:
b0502_map = {
    1: "Cuenta corriente",
    2: "Cuenta ahorro",
    3: "Depósito a plazo",
    4: "Fondo inver.",
    5: "Acciones",
    6: "Hipoteca",
    7: "Ptmo personal",
    8: "Tjta de crédito",
    9: "Seg. vida",
    10: "Seg. médico",
    11: "Plan pensiones",
    12: "Otros productos",
    -98: "N/A (filtro)",
    -97: "No sabe",
    -99: "No contesta",
    -5: "Error CAPI"
}

df["Último producto contratado"] = df["b0502"].replace(b0502_map)

In [13]:
df = df.rename(columns={
        'a01': 'Año_entrev.'  })

In [14]:
df=df.drop(columns=['b0502'])

In [15]:
df=df.drop(columns=['a0100'])

In [16]:
df.columns.tolist()

['Año_entrev.',
 'age',
 'Plan pensiones',
 'Fondo inver.',
 'Acciones',
 'Activo renta fija',
 'Cuenta o depósito ahorro',
 'Hipoteca',
 'Ptmo personal',
 'Tjta credito',
 'Seg. vida',
 'Seg. médico',
 'Plan pensiones (L2Y)',
 'Fondo inver.(L2Y)',
 'Acciones (L2Y)',
 'Activo renta fija (L2Y)',
 'Cta o depósito ahorro (L2Y)',
 'Hipoteca (L2Y)',
 'Ptmo personal (L2Y)',
 'Tjta credito (L2Y)',
 'Seg. vida (L2Y)',
 'Seg. médico (L2Y)',
 'Tienen Product fin.',
 'Último producto contratado']

In [17]:
df.head()

,Año_entrev.,age,Plan pensiones,Fondo inver.,Acciones,Activo renta fija,Cuenta o depósito ahorro,Hipoteca,Ptmo personal,Tjta credito,...,Acciones (L2Y),Activo renta fija (L2Y),Cta o depósito ahorro (L2Y),Hipoteca (L2Y),Ptmo personal (L2Y),Tjta credito (L2Y),Seg. vida (L2Y),Seg. médico (L2Y),Tienen Product fin.,Último producto contratado
0,2016,18,Sí,N/A,No,No,Sí,No,No,No,...,No,No,No,No,No,No,No,No,Sí,N/A (filtro)
1,2016,33,No,No,Sí,No,N/A,Sí,Sí,Sí,...,No,No,N/A,Sí,No,No,No,No,Sí,Cuenta corriente
2,2016,49,No,N/A,No,N/A,No,No,No,No,...,No,N/A,No,No,No,No,No,No,Sí,N/A (filtro)
3,2016,54,No,No,No,N/A,Sí,No,No,N/A,...,No,N/A,Sí,No,No,N/A,No,No,Sí,Tjta de crédito
4,2016,64,No,N/A,N/A,N/A,Sí,No,Sí,No,...,N/A,N/A,No,No,No,No,No,No,Sí,N/A (filtro)

In [18]:
df.to_csv("C:/Users/Portátil/ProjecteData/Equip_23/Data/8 April/02_Product_Activos_cleaning_16.csv",index=False)