In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Portátil\Desktop\Work\Simulacio_empr\Sprint4\02_Datos procesados (2)\01_Demografia_2021_GEN.csv",sep=";")
df.head()

,a01: anio de la entrevista,a01: anio de la entrevista.1,a02: mes de la entrevista,"a0000: es requisito que pregunte su genero, es vd. hombre o mujer?",a0400: en que anio nacio?,a04: edad calculada,a0800: me podria decir su edad aproximada?,a0100: en que pais nacio?,a0320,a1030,...,a0900f: con quien vive habitualmente?f.nietos/bisnietos,a0900l,a0900j: con quien vive habitualmente?j.con amigos/colegas/estudiantes,a0900h: con quien vive habitualmente?h.yerno/nuera,a0900g: con quien vive habitualmente?g.hermanos,a0900i: con quien vive habitualmente?i.con otros parientes,a0900a: con quien vive habitualmente?a. solo/a,a0900k: con quien vive habitualmente?k.otros,a1800: profesion o trabajo (2 digitos cno-11),a0200: en que provincia nacio?
0,2022,2022,6,0,1982,40,-98,1,0,2,...,0,0,0,0,0,0,0,0,44,1
1,2022,2022,3,0,1967,54,-98,1,0,1,...,0,0,0,0,0,0,0,0,22,5
2,2022,2022,2,1,1967,54,-98,1,0,6,...,0,0,0,0,0,0,1,0,36,11
3,2022,2022,5,1,1974,48,-98,1,0,2,...,0,0,0,0,0,0,0,0,59,5
4,2022,2022,6,1,1972,49,-98,1,0,1,...,0,0,0,0,0,0,0,0,92,4

In [2]:
#Eliminar text deixar nomes codi
df.columns = df.columns.str.split(':').str[0]
df.head(2)

,a01,a01,a02,a0000,a0400,a04,a0800,a0100,a0320,a1030,...,a0900f,a0900l,a0900j,a0900h,a0900g,a0900i,a0900a,a0900k,a1800,a0200
0,2022,2022,6,0,1982,40,-98,1,0,2,...,0,0,0,0,0,0,0,0,44,1
1,2022,2022,3,0,1967,54,-98,1,0,1,...,0,0,0,0,0,0,0,0,22,5

In [3]:
df.columns.tolist()

['a01',
 'a01',
 'a02',
 'a0000',
 'a0400',
 'a04',
 'a0800',
 'a0100',
 'a0320',
 'a1030',
 'a1040',
 'a0910',
 'a1100',
 'a1200',
 'a1300',
 'a1400',
 'a1410',
 'a1420a',
 'a1420b',
 'a1420c',
 'a1420d',
 'a1420e',
 'a1420f',
 'a1420g',
 'a1500',
 'a1510',
 'a1600',
 'a1520',
 'a1530',
 'a1700',
 'a1710',
 'a1900',
 'a0940',
 'a0930',
 'a0300',
 'a0310',
 'a0930_b',
 'a0950',
 'a0900b',
 'a0900c',
 'a0900d',
 'a0900e',
 'a0900f',
 'a0900l',
 'a0900j',
 'a0900h',
 'a0900g',
 'a0900i',
 'a0900a',
 'a0900k',
 'a1800',
 'a0200']

#### Asignación al grupo por situacion laboral

In [4]:
import numpy as np

df['labor_status'] = np.where(df['a1500'] == 1, "autónomo",
                       np.where(df['a1500'] == 1, "asalariado",
                       np.where(df['a1500'] == 5, "desempleado",
                       np.where(df['a1500'] == 6, "jubilado",
                       np.where(df['a1500'].isin([4,7,8,9,10]), "otros inactivos","missing")))))

In [5]:
#Eliminar antnterior column
df=df.drop(columns=['a1500'])

#### Asignación al grupo por estructura familiar

In [7]:
df['familia'] = np.where(
    df['a0900b'] == 1, "Vive con pareja",
    np.where(
        df['a0900a'] == 1, "Vive solo/a",
        np.where(
            (df['a0900b'] == 0) &
            (
                (df['a0900d'] == 1) |
                (df['a0900e'] == 1) |
                (df['a0900j'] == 1) |
                (df['a0900h'] == 1) |
                (df['a0900g'] == 1) |
                (df['a0900i'] == 1)
            ),
            "No vive con pareja pero vive con otros adultos",
            np.where(
                df['a0900a'] != -99,
                "No vive con pareja ni con otros adultos",
                None   # millor que np.nan per evitar conflictes
            )
        )
    )
).astype(object)

In [8]:
df = df.drop(columns=[
    'a0900a','a0900b','a0900c','a0900d','a0900e',
    'a0900f','a0900g','a0900h','a0900i','a0900j','a0900k'
])

#### Asignación nombres nuevos columnas

In [9]:
df = df.rename(columns={
    'a0400': 'Año_naci.',
    'a04': 'Edad',
    'a01': 'Año_entrev.',
    'a02': 'Mes_entrev.'
})

#### Asignación al grupo por educación

In [10]:
df['edu_level'] = df['a1100'].replace({
    1: "Primaria", 2: "Primaria", 3: "Primaria",
    4: "Secundaria", 5: "Secundaria",
    6: "Universitaria", 7: "Universitaria", 8: "Universitaria", 9: "Universitaria"
})

In [11]:
df = df.drop(columns=[
    'a1400','a1600','a1700','a0300','a0800','a0100','a0900l','a0310','a0930_b','a0950' 
])

In [12]:
df = df.drop(columns=[
    'a1510','a1520','a1530','a1710','a0940','a0930','a1410','a1420a','a1420b','a1420c','a1420d','a1420e','a1420f','a1420g' 
])

In [13]:
df = df.drop(columns=[
    'a0320','a1030','a1040','a0910','a1200','a1300' 
])

In [14]:
df = df.drop(columns=[
    'a1100'
])

In [16]:
df.head(1)

,Año_entrev.,Año_entrev.,Mes_entrev.,a0000,Año_naci.,Edad,a1900,a1800,a0200,labor_status,familia,edu_level
0,2022,2022,6,0,1982,40,0,44,1,missing,Vive con pareja,Universitaria

### Indicamos CCAA

In [17]:
df['CCAA'] = df['a0200'].replace({
    1: "Andalusia", 2: "Aragon", 3: "Asturias",4: "Baleric Islands", 5: "Canary Island",6: "Cantabria", 7: "Castille-Leon", 8: "Castille-la Mancha", 9: "Catalonia",10:'Valencia Country',11:'Extremadura',12:'Galicia',13:'Madrid Region',14:'Murcia Region',15:'Navarre',16:'Basque Country',17:'La Rioja',-96:'(NS/NC)',-98:'(N/A)'
})

### Indicamos oficios

In [18]:
# dicionari 
ocupaciones_cno11 = {
    -99: "Missing / Error",
    -98: "No aplicable",
    -5: "No disponible",
    0: "Fuerzas Armadas",

    # Grupo 1 – Directivos y gerentes
    11: "Directores generales y gerentes",
    12: "Directores de departamento",
    13: "Gerentes de empresas pequeñas",
    14: "Gerentes comerciales",
    15: "Gerentes de hostelería y restauración",

    # Grupo 2 – Profesionales científicos e intelectuales
    21: "Profesionales de ciencias y ingeniería",
    22: "Profesionales de la salud",
    23: "Profesores y docentes",
    24: "Profesionales de economía, derecho y sociales",
    25: "Profesionales TIC",
    26: "Profesionales artísticos y culturales",
    27: "Profesionales del deporte",
    28: "Profesionales de información y comunicación",
    29: "Otros profesionales",

    # Grupo 3 – Técnicos y profesionales de apoyo
    31: "Técnicos de ciencias y ingeniería",
    32: "Técnicos de salud",
    33: "Técnicos de educación",
    34: "Técnicos de economía y administración",
    35: "Técnicos TIC",
    36: "Técnicos artísticos",
    37: "Técnicos del deporte",
    38: "Técnicos de información y comunicación",

    # Grupo 4 – Empleados administrativos
    41: "Administrativos generales",
    42: "Administrativos financieros",
    43: "Administrativos de apoyo",
    44: "Recepcionistas",
    45: "Otros administrativos",

    # Grupo 5 – Trabajadores de servicios y vendedores
    50: "Servicios diversos",
    51: "Personal de restauración",
    52: "Personal de venta",
    53: "Personal de cuidados y atención",
    54: "Personal de seguridad",
    55: "Personal de limpieza",
    56: "Servicios personales",
    57: "Servicios de protección",
    58: "Servicios de transporte",
    59: "Otros servicios",

    # Grupo 6 – Agricultura, ganadería, pesca
    61: "Agricultura",
    62: "Ganadería",
    63: "Silvicultura",
    64: "Pesca",

    # Grupo 7 – Artesanos y trabajadores cualificados
    71: "Construcción",
    72: "Metalurgia",
    73: "Electricidad y electrónica",
    74: "Mecánica",
    75: "Madera y muebles",
    76: "Textil y confección",
    77: "Alimentación",
    78: "Otros oficios",

    # Grupo 8 – Operadores de maquinaria
    81: "Operadores de instalaciones fijas",
    82: "Operadores de maquinaria móvil",
    83: "Conductores de vehículos",
    84: "Operadores de equipos industriales",

    # Grupo 9 – Ocupaciones elementales
    91: "Personal de limpieza",
    92: "Ayudantes de cocina y servicios",
    93: "Repartidores",
    94: "Peones de construcción",
    95: "Peones agrícolas",
    96: "Peones industriales",
    97: "Recolectores y manipuladores",
    98: "Ocupaciones elementales diversas"
}

In [19]:
#aplicar oficis
df["ocupacion"] = df["a1800"].replace(ocupaciones_cno11)

### Tu trabajo esta relacionado con aspectos financieros

In [20]:
df["trabajo_rel."]=df['a1900'].replace({0:"No",1:"Si",-96:"NS/NC",-98:"N/A"})

### hombre o mujer

In [21]:
df["gender"]=df['a0000'].replace({0:"Mujer",1:"Hombre",-96:"NS/NC",-98:"N/A"})

In [22]:
df=df.drop(columns=['a0200','a1800','a1900','a0000'])

In [23]:
df.head(2)

,Año_entrev.,Año_entrev.,Mes_entrev.,Año_naci.,Edad,labor_status,familia,edu_level,CCAA,ocupacion,trabajo_rel.,gender
0,2022,2022,6,1982,40,missing,Vive con pareja,Universitaria,Andalusia,Recepcionistas,No,Mujer
1,2022,2022,3,1967,54,missing,No vive con pareja pero vive con otros adultos,Universitaria,Canary Island,Profesionales de la salud,No,Mujer

In [25]:
#eliminar duplicados
df = df.loc[:, ~df.columns.duplicated()]

In [26]:
df.head(2)

,Año_entrev.,Mes_entrev.,Año_naci.,Edad,labor_status,familia,edu_level,CCAA,ocupacion,trabajo_rel.,gender
0,2022,6,1982,40,missing,Vive con pareja,Universitaria,Andalusia,Recepcionistas,No,Mujer
1,2022,3,1967,54,missing,No vive con pareja pero vive con otros adultos,Universitaria,Canary Island,Profesionales de la salud,No,Mujer

In [29]:
df.to_csv("C:/Users/Portátil/ProjecteData/Equip_23/Data/8 April/01_Demografia_cleaning_21.csv",index=False)