# Quins ciutat i barris presenten un potencial d'optimització més gran considerant les ressenyes, la puntuació de la zona i la disponibilitat mínima/màxima de nits?

### Número mínimo y máximo de noches: 
    - El número mínimo de noches viene dado por la necesidad de evitar días sin ocupación, en este caso se debe tener un balance entre no tener días sin ocupación y evitar que los huespedes puedan contratar varias noches seguidas, un buen número de noches mínimas es de 2 (corresponde a las noches de fin de semana)
    - El número máximo de noches nos lo marca la normativa estatal, los alojamientos turísticos no pueden ser alquilados por un periodo mayor a 30 días, si se alquilase por más de 31 días el regimen pasaría a ser el de alojamiento de temporada.

### Puntuación de reseñas 
    - Se establece el valor optimo de las reseñas en 80 puntos tal como se establece en el estudio: https://www.cimec.es/grados-de-satisfaccion/

### Puntuación de zona
    - La puntuación óptima de la zona se establecerá con el mismo criterio que en las reseñas.

In [5]:
import pandas as pd

In [6]:
data = pd.read_csv("tourist_accommodation_10112025_clean.csv")

In [7]:
data

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,...,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date,is_valid,ocupacion_mes
0,11964,A ROOM WITH A VIEW,Private bedroom in our attic apartment. Right ...,45553,Centro,NaN,Private room,2,2,1.0,...,10.0,10.0,10.0,0,0.406109,Spain,Málaga,2018-07-31,True,23
1,21853,Bright and airy room,We have a quiet and sunny room with a good vie...,83531,Cármenes,Latina,Private room,1,1,1.0,...,10.0,8.0,9.0,0,0.244444,Spain,Madrid,2020-01-10,True,30
2,32347,Explore Cultural Sights from a Family-Friendly...,Open French doors and step onto a plant-filled...,139939,San Vicente,Casco Antiguo,Entire home/apt,4,1,2.0,...,10.0,10.0,10.0,1,0.836473,Spain,Sevilla,2019-07-29,True,4
3,35379,Double 02 CasanovaRooms Barcelona,Room at a my apartment. Kitchen and 2 bathroom...,152232,L'Antiga Esquerra De L'Eixample,Eixample,Private room,2,2,1.0,...,10.0,10.0,9.0,1,4.273171,Spain,Barcelona,2020-01-10,True,21
4,35801,Can Torras Farmhouse Studio Suite,Lay in bed & watch sunlight change the mood of...,153805,Quart,NaN,Private room,5,1,2.0,...,10.0,10.0,10.0,0,0.207294,Spain,Girona,2019-02-19,True,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9401,47710189,Beautiful house in the centre in Santa Cristin...,Beautiful house in the center of Santa Cristin...,263841355,Santa Cristina D'Aro,NaN,Entire home/apt,8,2,4.0,...,10.0,10.0,9.0,1,0.070061,Spain,Girona,2021-01-31,True,30
9402,47752964,Costa Brava - Palafrugell - playa y monta�a,Piso con acceso directo a piscina. Lugar muy t...,282214688,Palafrugell,NaN,Entire home/apt,7,2,3.0,...,10.0,10.0,9.0,0,0.070061,Spain,Girona,2021-02-27,True,1
9403,47792016,MODERN AND BRIGHT NEW FLAT IN THE CENTER OF PA...,Modern and new apartment in the old town of Pa...,263841355,Palamós,NaN,Entire home/apt,6,1,3.0,...,10.0,10.0,9.0,1,0.070061,Spain,Girona,2021-01-31,True,30
9404,47884481,MIT House Olavide III in Madrid,The apartment is in a characteristic building ...,377605855,Trafalgar,Chamberí,Entire home/apt,4,1,1.0,...,10.0,10.0,9.0,0,0.181622,Spain,Madrid,2021-02-09,True,14
9405,48061552,Gran v�a Double Room,NaN,387478257,Universidad,Centro,Private room,2,2,1.0,...,10.0,10.0,9.0,0,0.181622,Spain,Madrid,2021-02-09,True,2

In [8]:
data.columns

Index(['apartment_id', 'name', 'description', 'host_id', 'neighbourhood_name',
       'neighbourhood_district', 'room_type', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'amenities_list', 'price', 'minimum_nights',
       'maximum_nights', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'number_of_reviews', 'first_review_date', 'last_review_date',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'is_instant_bookable', 'reviews_per_month',
       'country', 'city', 'insert_date', 'is_valid', 'ocupacion_mes'],
      dtype='object')

In [32]:
optimize_data = data[["neighbourhood_name","review_scores_location","review_scores_rating","minimum_nights","maximum_nights","city"]][(data["review_scores_location"]<8)
&(data["review_scores_rating"]<80)&((data["minimum_nights"]<2)|(data["minimum_nights"]>3))&((data["maximum_nights"]>30)|(data["maximum_nights"]<3))]

In [34]:
optimize_data

,neighbourhood_name,review_scores_location,review_scores_rating,minimum_nights,maximum_nights,city
823,Castelló D'Empúries,7.0,70.0,7,1125,Girona
1554,El Barri Gòtic,6.0,60.0,1,1125,Barcelona
1669,San Diego,5.0,40.0,30,1125,Madrid
1702,Calonge,7.0,75.0,7,1125,Girona
2716,Osor,7.0,73.0,1,31,Girona
2900,El Raval,7.0,77.0,32,1120,Barcelona
3903,L'Escala,6.0,60.0,1,1125,Girona
4010,El Carmel,7.0,76.0,1,1125,Barcelona
4064,Valverde,7.0,73.0,1,1125,Madrid
4098,El Besòs I El Maresme,4.0,60.0,4,32,Barcelona
4133,La Nova Esquerra De L'Eixample,7.0,72.0,1,1125,Barcelona
4216,Castell-Platja D'Aro,2.0,60.0,7,1125,Girona
4509,El Raval,7.0,73.0,1,1125,Barcelona
4617,La Sagrada Família,6.0,47.0,1,1125,Barcelona
4672,El Raval,4.0,40.0,5,1125,Barcelona
5012,Roses,4.0,60.0,1,1125,Girona
5413,Sant Llorenç Des Cardassar,7.0,53.0,1,1125,Mallorca
6760,Palma De Mallorca,5.0,40.0,4,1125,Mallorca
6994,La Dreta De L'Eixample,6.0,40.0,1,1125,Barcelona
7370,El Carmel,5.0,30.0,32,1125,Barcelona
7397,Vilajuïga,6.0,70.0,1,1125,Girona
8120,L'Escala,7.0,60.0,7,1125,Girona
8716,Els Orriols,6.0,60.0,1,33,Valencia
9167,Palomeras Bajas,7.0,65.0,1,1125,Madrid
9299,La Sagrada Família,5.0,50.0,32,360,Barcelona
9328,An Roque,2.0,20.0,1,1125,Sevilla

In [36]:
df = optimize_data.groupby(["city", "neighbourhood_name"])

In [38]:
df.first()

                                          review_scores_location  \
city      neighbourhood_name
Barcelona El Barri Gòtic                                     6.0
          El Besòs I El Maresme                              4.0
          El Carmel                                          7.0
          El Raval                                           7.0
          La Dreta De L'Eixample                             6.0
          La Nova Esquerra De L'Eixample                     7.0
          La Sagrada Família                                 6.0
Girona    Calonge                                            7.0
          Castell-Platja D'Aro                               2.0
          Castelló D'Empúries                                7.0
          L'Escala                                           6.0
          Osor                                               7.0
          Roses                                              4.0
          Vilajuïga                                          6.0
Madrid    Palomeras Bajas                                    7.0
          San Diego                                          5.0
          Valverde                                           7.0
Mallorca  Palma De Mallorca                                  5.0
          Sant Llorenç Des Cardassar                         7.0
Sevilla   An Roque                                           2.0
Valencia  Els Orriols                                        6.0

                                          review_scores_rating  \
city      neighbourhood_name
Barcelona El Barri Gòtic                                  60.0
          El Besòs I El Maresme                           60.0
          El Carmel                                       76.0
          El Raval                                        77.0
          La Dreta De L'Eixample                          40.0
          La Nova Esquerra De L'Eixample                  72.0
          La Sagrada Família                              47.0
Girona    Calonge                                         75.0
          Castell-Platja D'Aro                            60.0
          Castelló D'Empúries                             70.0
          L'Escala                                        60.0
          Osor                                            73.0
          Roses                                           60.0
          Vilajuïga                                       70.0
Madrid    Palomeras Bajas                                 65.0
          San Diego                                       40.0
          Valverde                                        73.0
Mallorca  Palma De Mallorca                               40.0
          Sant Llorenç Des Cardassar                      53.0
Sevilla   An Roque                                        20.0
Valencia  Els Orriols                                     60.0

                                          minimum_nights  maximum_nights
city      neighbourhood_name
Barcelona El Barri Gòtic                               1            1125
          El Besòs I El Maresme                        4              32
          El Carmel                                    1            1125
          El Raval                                    32            1120
          La Dreta De L'Eixample                       1            1125
          La Nova Esquerra De L'Eixample               1            1125
          La Sagrada Família                           1            1125
Girona    Calonge                                      7            1125
          Castell-Platja D'Aro                         7            1125
          Castelló D'Empúries                          7            1125
          L'Escala                                     1            1125
          Osor                                         1              31
          Roses                                        1            1125
          Vilajuïga                                    1            1125
Madrid    Palomeras Bajas                              1            1125
          San Diego                                   30            1125
          Valverde                                     1            1125
Mallorca  Palma De Mallorca                            4            1125
          Sant Llorenç Des Cardassar                   1            1125
Sevilla   An Roque                                     1            1125
Valencia  Els Orriols                                  1              33