In [1]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\irene\Desktop\DataAnalytics\Bootcamp\Simulacro empresarial\ProjecteData\Equip_19\Data\datos_INE_consolidados_17112025.csv")

In [3]:
df.head()

,año,mes,provincia,pais_residencia,pernoctaciones,total_viajeros,media_pernoctaciones,fecha
0,2015,Enero,Islas Baleares,Total,25933.0,3705.0,7.00,2015-01-01
1,2015,Febrero,Islas Baleares,Total,30280.0,4382.0,6.91,2015-02-01
2,2015,Marzo,Islas Baleares,Total,46156.0,6536.0,7.06,2015-03-01
3,2015,Abril,Islas Baleares,Total,226542.0,36181.0,6.26,2015-04-01
4,2015,Mayo,Islas Baleares,Total,888610.0,145473.0,6.11,2015-05-01

In [11]:
df['pais_residencia'].unique()

array(['Total', 'España', 'No residentes en España',
       'Unión Europea (sin España)', 'Alemania', 'Austria', 'Bélgica',
       'Dinamarca', 'Finlandia', 'Francia', 'Grecia', 'Irlanda', 'Italia',
       'Luxemburgo', 'Países Bajos', 'Polonia', 'Portugal', 'Reino Unido',
       'República Checa', 'Suecia', 'Resto de la UE', 'Noruega', 'Rusia',
       'Suiza', 'Resto de Europa', 'Estados Unidos', 'Resto de América',
       'Países africanos', 'Resto del mundo', 'Extranjeros'], dtype=object)

In [ ]:
# Solo españoles y extranjeros
df_nac_internac = df.loc[(df['pais_residencia'] == 'España') | df['pais_residencia'] == 'No residentes en España']

# Solo países o regiones
df_paises = df.loc[(df['pais_residencia'] != 'Total') & (df['pais_residencia'] != 'No residentes en España') 
                   & (df['pais_residencia'] != 'Unión Europea (sin España)') & (df['pais_residencia'] != 'Extranjeros')]

,año,mes,provincia,pais_residencia,pernoctaciones,total_viajeros,media_pernoctaciones,fecha
12,2015,Enero,Islas Baleares,España,5125.0,1323.0,3.87,2015-01-01
13,2015,Febrero,Islas Baleares,España,7520.0,1938.0,3.88,2015-02-01
14,2015,Marzo,Islas Baleares,España,6915.0,1820.0,3.80,2015-03-01
15,2015,Abril,Islas Baleares,España,26217.0,6157.0,4.26,2015-04-01
16,2015,Mayo,Islas Baleares,España,65038.0,15287.0,4.25,2015-05-01

In [ ]:
df_paises_agrupado = df_paises.groupby('pais_residencia').agg(
    Suma_Viajeros=('total_viajeros', 'sum'),
    Media_Pernoctaciones=('pernoctaciones', 'mean') 
)