# Análisis de Perfil i Desempeño Professional

**Desafío 1**  
Quin és el perfil sociodemogràfic dels empleats que tenim a l'empresa, i com podem utilitzar aquesta informació per dissenyar polítiques de talent més adaptades a les seves necessitats i potenciar el seu compromís i desenvolupament professional?

*Punts a respondre (dibuix de la pregunta)* 
- Perfil sociodemogràfic (Columnes: 'ID','Transportation_expense', 'Distance_Residence_Work', 'Service_time', 'Age', 'Education', 'Education_name', 'Son', 'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height','BMI_calculated')
- Com podem utilitzar aquesta informació per dissenyar polítiques de talent més adaptades a les seves necessitats i potenciar el seu compromís i desenvolupament professional (valorar les altres variables no demogràfiques (e.g. 'Absenteeism_hours', hit target) o simplement fer-ho de forma teòrica?)

## Librerías

In [7]:
import pandas as pd
import matplotlib.pyplot as plt

## Documentos

In [2]:
DATA_INPUT_FILE = '../../Data/clean/clean_data_25052026.csv'

In [3]:
df = pd.read_csv(DATA_INPUT_FILE)

In [5]:
df.sample(5)

,ID,Reason_absence,Reason_absence_name,Month_absence,Month_absence_name,Day_week,Day_week_name,Seasons,Seasons_name,Transportation_expense,...,Education_name,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
659,36,28.0,Consulta dental,12.0,Diciembre,3,Martes,2,Primavera,118,...,Secundaria,1,1,0,0,98,178,31,30.9,1
533,22,23.0,Consulta médica,9.0,Septiembre,2,Lunes,1,Invierno,179,...,Posgrado,0,0,0,0,56,171,19,19.2,2
16,10,13.0,Sistema musculoesquelético,8.0,Agosto,2,Lunes,1,Invierno,361,...,Secundaria,1,1,0,4,80,172,27,27.0,40
414,22,13.0,Sistema musculoesquelético,1.0,Enero,2,Lunes,3,Verano,179,...,Posgrado,0,0,0,0,56,171,19,19.2,3
385,3,27.0,Fisioterapia,2.0,Febrero,2,Lunes,3,Verano,179,...,Secundaria,0,1,0,0,89,170,31,30.8,3

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           697 non-null    float64
 2   Reason_absence_name      697 non-null    str
 3   Month_absence            737 non-null    float64
 4   Month_absence_name       737 non-null    str
 5   Day_week                 740 non-null    int64
 6   Day_week_name            740 non-null    str
 7   Seasons                  740 non-null    int64
 8   Seasons_name             740 non-null    str
 9   Transportation_expense   740 non-null    int64
 10  Distance_Residence_Work  740 non-null    int64
 11  Service_time             740 non-null    int64
 12  Age                      740 non-null    int64
 13  Work_load_Average_day    740 non-null    float64
 14  Hit_target               740 non-null    int64
 15  Disciplinary_failure     740 non-null    int64
 16  Education                740 non-null    int64
 17  Education_name           740 non-null    str
 18  Son                      740 non-null    int64
 19  Social_drinker           740 non-null    int64
 20  Social_smoker            740 non-null    int64
 21  Pet                      740 non-null    int64
 22  Weight                   740 non-null    int64
 23  Height                   740 non-null    int64
 24  Body_mass_index          740 non-null    int64
 25  BMI_calculated           740 non-null    float64
 26  Absenteeism_hours        740 non-null    int64
dtypes: float64(4), int64(18), str(5)
memory usage: 156.2 KB

In [8]:
df.columns

Index(['ID', 'Reason_absence', 'Reason_absence_name', 'Month_absence',
       'Month_absence_name', 'Day_week', 'Day_week_name', 'Seasons',
       'Seasons_name', 'Transportation_expense', 'Distance_Residence_Work',
       'Service_time', 'Age', 'Work_load_Average_day', 'Hit_target',
       'Disciplinary_failure', 'Education', 'Education_name', 'Son',
       'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height',
       'Body_mass_index', 'BMI_calculated', 'Absenteeism_hours'],
      dtype='str')

## Viz

### Perfil sociodemogràfic

In [9]:
perfil_col = ['ID','Transportation_expense', 'Distance_Residence_Work', 'Service_time', 'Age', 'Education', 'Education_name', 'Son', 'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height','BMI_calculated']

In [10]:
df_perfil = df.loc[:, perfil_col]
df_perfil.sample(5)

,ID,Transportation_expense,Distance_Residence_Work,Service_time,Age,Education,Education_name,Son,Social_drinker,Social_smoker,Pet,Weight,Height,BMI_calculated
552,3,179,51,18,38,1,Secundaria,0,1,0,0,89,170,30.8
116,28,225,26,9,28,1,Secundaria,1,0,0,2,69,169,24.2
437,3,179,51,18,38,1,Secundaria,0,1,0,0,89,170,30.8
684,9,228,14,16,58,1,Secundaria,2,0,0,1,65,172,22.0
358,28,225,26,9,28,1,Secundaria,1,0,0,2,69,169,24.2

In [11]:
df_perfil.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Transportation_expense   740 non-null    int64
 2   Distance_Residence_Work  740 non-null    int64
 3   Service_time             740 non-null    int64
 4   Age                      740 non-null    int64
 5   Education                740 non-null    int64
 6   Education_name           740 non-null    str
 7   Son                      740 non-null    int64
 8   Social_drinker           740 non-null    int64
 9   Social_smoker            740 non-null    int64
 10  Pet                      740 non-null    int64
 11  Weight                   740 non-null    int64
 12  Height                   740 non-null    int64
 13  BMI_calculated           740 non-null    float64
dtypes: float64(1), int64(12), str(1)
memory usage: 81.1 KB

In [12]:
df_perfil.duplicated().sum()

np.int64(704)

In [13]:
df_perfil.drop_duplicates(inplace=True)

In [14]:
df_perfil.shape

(36, 14)