# Análisis de perfil y desempeño 01/06/2026

# Librerías

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
from datetime import date
import scipy.stats as stats
import numpy as np
import plotly.graph_objs as go

# Documento

In [2]:
df_RRHH = pd.read_csv('../../Data/clean/clean_data_01062026.csv')
df_RRHH

,ID,Reason_absence,Reason_absence_name,Month_absence,Month_absence_name,Day_week,Day_week_name,Seasons,Seasons_name,Transportation_expense,...,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours,importacion
0,14,11.0,Sistema digestivo,5.0,Mayo,2,Lunes,2,Primavera,155,...,2,1,0,0,95,196,25,24.7,120,2026-05-25
1,36,13.0,Sistema musculoesquelético,10.0,Octubre,4,Miércoles,4,Otoño,118,...,1,1,0,0,98,178,31,30.9,120,2026-05-25
2,9,6.0,Sistema nervioso,1.0,Enero,3,Martes,1,Invierno,228,...,2,0,0,1,65,172,22,22.0,120,2026-05-25
3,28,9.0,Sistema circulatorio,1.0,Enero,3,Martes,1,Invierno,225,...,1,0,0,2,69,169,24,24.2,112,2026-05-25
4,9,12.0,Piel y tejido subcutáneo,9.0,Septiembre,3,Martes,3,Verano,228,...,2,0,0,1,65,172,22,22.0,112,2026-05-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839,14,11.0,Sistema digestivo,5.0,Mayo,2,Lunes,2,Primavera,155,...,2,1,0,0,95,196,25,24.7,120,2026-06-01
840,36,13.0,Sistema musculoesquelético,10.0,Octubre,4,Miércoles,4,Otoño,118,...,1,1,0,0,98,178,31,30.9,120,2026-06-01
841,9,6.0,Sistema nervioso,1.0,Enero,3,Martes,1,Invierno,228,...,2,0,0,1,65,172,22,22.0,120,2026-06-01
842,28,9.0,Sistema circulatorio,1.0,Enero,3,Martes,1,Invierno,225,...,1,0,0,2,69,169,24,24.2,112,2026-06-01
843,9,12.0,Piel y tejido subcutáneo,9.0,Septiembre,3,Martes,3,Verano,228,...,2,0,0,1,65,172,22,22.0,112,2026-06-01

In [3]:
df_RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 844 entries, 0 to 843
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       844 non-null    int64
 1   Reason_absence           802 non-null    float64
 2   Reason_absence_name      802 non-null    str
 3   Month_absence            841 non-null    float64
 4   Month_absence_name       841 non-null    str
 5   Day_week                 844 non-null    int64
 6   Day_week_name            844 non-null    str
 7   Seasons                  844 non-null    int64
 8   Seasons_name             844 non-null    str
 9   Transportation_expense   844 non-null    int64
 10  Distance_Residence_Work  844 non-null    int64
 11  Service_time             844 non-null    int64
 12  Age                      844 non-null    int64
 13  Work_load_Average_day    844 non-null    float64
 14  Hit_target               844 non-null    int64
 15  Disciplinary_failure     844 non-null    int64
 16  Education                844 non-null    int64
 17  Education_name           844 non-null    str
 18  Son                      844 non-null    int64
 19  Social_drinker           844 non-null    int64
 20  Social_smoker            844 non-null    int64
 21  Pet                      844 non-null    int64
 22  Weight                   844 non-null    int64
 23  Height                   844 non-null    int64
 24  Body_mass_index          844 non-null    int64
 25  BMI_calculated           844 non-null    float64
 26  Absenteeism_hours        844 non-null    int64
 27  importacion              844 non-null    str
dtypes: float64(4), int64(18), str(6)
memory usage: 184.8 KB

In [4]:
df_RRHH.shape

(844, 28)

In [5]:
df_RRHH.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,844.0,26.125592,26.389515,1.000,10.000,20.000,33.000,136.000
Reason_absence,802.0,20.314214,7.176987,1.000,13.000,23.000,27.000,28.000
Month_absence,841.0,6.527943,3.400209,1.000,4.000,7.000,9.000,12.000
Day_week,844.0,3.928910,1.416617,2.000,3.000,4.000,5.000,6.000
Seasons,844.0,2.523697,1.095946,1.000,2.000,3.000,3.000,4.000
Transportation_expense,844.0,220.477488,67.456296,118.000,179.000,225.000,260.000,388.000
Distance_Residence_Work,844.0,29.422986,14.748504,5.000,16.000,26.000,49.000,52.000
Service_time,844.0,12.582938,4.425366,1.000,9.000,12.500,16.000,29.000
Age,844.0,36.453791,6.552751,27.000,31.000,37.000,40.000,58.000
Work_load_Average_day,844.0,271.957630,39.054208,205.917,244.387,264.604,294.217,378.884
Hit_target,844.0,94.575829,3.799567,81.000,93.000,95.000,97.000,100.000
Disciplinary_failure,844.0,0.046209,0.210061,0.000,0.000,0.000,0.000,1.000
Education,844.0,1.283175,0.663684,1.000,1.000,1.000,1.000,4.000
Son,844.0,1.000000,1.084781,0.000,0.000,1.000,2.000,4.000
Social_drinker,844.0,0.561611,0.496484,0.000,0.000,1.000,1.000,1.000
Social_smoker,844.0,0.072275,0.259096,0.000,0.000,0.000,0.000,1.000
Pet,844.0,0.728673,1.278931,0.000,0.000,0.000,1.000,8.000
Weight,844.0,79.026066,12.880757,56.000,69.000,83.000,89.000,108.000
Height,844.0,172.113744,5.967794,163.000,169.000,170.500,172.000,196.000
Body_mass_index,844.0,26.676540,4.275603,19.000,24.000,25.000,31.000,38.000
BMI_calculated,844.0,26.689929,4.243038,19.200,23.700,25.100,30.800,38.000
Absenteeism_hours,844.0,7.376777,15.175063,0.000,2.000,3.000,8.000,120.000

In [6]:
df_RRHH.columns

Index(['ID', 'Reason_absence', 'Reason_absence_name', 'Month_absence',
       'Month_absence_name', 'Day_week', 'Day_week_name', 'Seasons',
       'Seasons_name', 'Transportation_expense', 'Distance_Residence_Work',
       'Service_time', 'Age', 'Work_load_Average_day', 'Hit_target',
       'Disciplinary_failure', 'Education', 'Education_name', 'Son',
       'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height',
       'Body_mass_index', 'BMI_calculated', 'Absenteeism_hours',
       'importacion'],
      dtype='str')

Listas de columnas numéricas y categóricas separadas de todo el dataset (con 'ID')

In [7]:
num = ['ID','Transportation_expense', 'Distance_Residence_Work', 'Service_time',
       'Age', 'Work_load_Average_day', 'Hit_target','Pet', 'Son',
       'Weight', 'Height', 'Absenteeism_hours', 'BMI_calculated']

cat = ['ID','Reason_absence', 'Month_absence', 'Day_week',
       'Seasons', 'Disciplinary_failure', 'Education',
       'Social_drinker', 'Social_smoker']

## df individuo  
**df_RRHH_ind_grouped** con:
- Variables sociodemográficas de cada individuo agrupadas
- Mediana de work_load_average_day y de hit target
- Conteo del número de ausencias (count de las solicitudes que tienen más de 0 horas)
- Sma de horas de absentismo.

In [8]:
df_RRHH.columns

Index(['ID', 'Reason_absence', 'Reason_absence_name', 'Month_absence',
       'Month_absence_name', 'Day_week', 'Day_week_name', 'Seasons',
       'Seasons_name', 'Transportation_expense', 'Distance_Residence_Work',
       'Service_time', 'Age', 'Work_load_Average_day', 'Hit_target',
       'Disciplinary_failure', 'Education', 'Education_name', 'Son',
       'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height',
       'Body_mass_index', 'BMI_calculated', 'Absenteeism_hours',
       'importacion'],
      dtype='str')

In [9]:
df_RRHH_ind = df_RRHH[[
        'ID', 'Transportation_expense', 'Distance_Residence_Work',
        'Service_time', 'Age', 'Work_load_Average_day', 'Hit_target',
        'Disciplinary_failure', 'Education', 'Education_name', 'Son',
        'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height',
        'BMI_calculated', 'Absenteeism_hours',
        ]].copy()

In [10]:
df_RRHH_ind.shape

(844, 18)

In [11]:
df_RRHH_ind.sample(5)

,ID,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,Hit_target,Disciplinary_failure,Education,Education_name,Son,Social_drinker,Social_smoker,Pet,Weight,Height,BMI_calculated,Absenteeism_hours
794,92,246,25,16,41,294.217,81,0,1,Secundaria,0,1,0,0,67,170,23.2,16
376,28,225,26,9,28,236.629,93,0,1,Secundaria,1,0,0,2,69,169,24.2,3
685,15,291,31,12,40,284.853,91,0,1,Secundaria,1,1,0,1,73,171,25.0,1
350,20,260,50,11,36,253.465,93,0,1,Secundaria,4,1,0,0,65,168,23.0,3
744,42,179,51,18,38,313.532,96,0,1,Secundaria,0,1,0,0,89,170,30.8,2

In [12]:
cols_first = [
    'Transportation_expense', 'Distance_Residence_Work',
    'Service_time', 'Age',
    'Disciplinary_failure', 'Education', 'Education_name', 'Son',
    'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height',
    'BMI_calculated'
]

df_RRHH_ind_grouped = (
    df_RRHH_ind
    .groupby('ID')
    .agg(
        **{col: (col, 'first') for col in cols_first},
        Work_load_Average_day=('Work_load_Average_day', 'median'),
        Hit_target=('Hit_target', 'median'),
        Absenteeism_hours=('Absenteeism_hours', 'sum'),
        Absence_count=('Absenteeism_hours', lambda x: (x > 0).sum())
    )
    .reset_index()
)

df_RRHH_ind_grouped[['Work_load_Average_day', 'Hit_target']] = (
    df_RRHH_ind_grouped[['Work_load_Average_day', 'Hit_target']]
    .round(3)
)

In [13]:
df_RRHH_ind_grouped

,ID,Transportation_expense,Distance_Residence_Work,Service_time,Age,Disciplinary_failure,Education,Education_name,Son,Social_drinker,Social_smoker,Pet,Weight,Height,BMI_calculated,Work_load_Average_day,Hit_target,Absenteeism_hours,Absence_count
0,1,235,11,14,37,0,3,Posgrado,1,0,0,1,88,172,29.7,249.797,95.0,121,22
1,2,235,29,12,48,0,1,Secundaria,1,0,1,5,88,163,33.1,218.104,92.0,25,4
2,3,179,51,18,38,0,1,Secundaria,0,1,0,0,89,170,30.8,253.465,96.0,482,112
3,4,118,14,13,40,0,1,Secundaria,1,1,0,8,98,170,33.9,271.219,95.0,0,0
4,5,235,20,13,43,0,1,Secundaria,1,1,0,0,106,167,38.0,265.017,93.0,104,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,132,118,13,18,50,0,1,Secundaria,1,1,0,0,98,178,30.9,244.387,98.0,3,1
132,133,118,10,10,37,0,1,Secundaria,0,0,0,0,83,172,28.1,241.476,92.0,3,1
133,134,118,10,10,37,0,1,Secundaria,0,0,0,0,83,172,28.1,268.519,93.0,8,1
134,135,225,26,9,28,0,1,Secundaria,1,0,0,2,69,169,24.2,378.884,92.0,8,1
135,136,225,26,9,28,0,1,Secundaria,1,0,0,2,69,169,24.2,280.549,98.0,3,1

In [14]:
df_RRHH_ind_grouped.columns

Index(['ID', 'Transportation_expense', 'Distance_Residence_Work',
       'Service_time', 'Age', 'Disciplinary_failure', 'Education',
       'Education_name', 'Son', 'Social_drinker', 'Social_smoker', 'Pet',
       'Weight', 'Height', 'BMI_calculated', 'Work_load_Average_day',
       'Hit_target', 'Absenteeism_hours', 'Absence_count'],
      dtype='str')

Listas de columnas numéricas y categóricas separadas para el estudio de individuo (_ID)

In [15]:
num_ID = ['ID','Transportation_expense', 'Distance_Residence_Work', 'Service_time',
       'Age', 'Pet', 'Son', 'Weight', 'Height', 'BMI_calculated','Work_load_Average_day',
       'Hit_target', 'Absenteeism_hours', 'Absence_count']

cat_ID = ['ID','Disciplinary_failure', 'Education',
       'Social_drinker', 'Social_smoker']

## df ausencias sin variables sociodemográficas  
**df_RRHH_abs**  
Variables asociadas directamente con la solicitud de ausencia

In [16]:
df_RRHH.columns

Index(['ID', 'Reason_absence', 'Reason_absence_name', 'Month_absence',
       'Month_absence_name', 'Day_week', 'Day_week_name', 'Seasons',
       'Seasons_name', 'Transportation_expense', 'Distance_Residence_Work',
       'Service_time', 'Age', 'Work_load_Average_day', 'Hit_target',
       'Disciplinary_failure', 'Education', 'Education_name', 'Son',
       'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height',
       'Body_mass_index', 'BMI_calculated', 'Absenteeism_hours',
       'importacion'],
      dtype='str')

In [17]:
col_absence = [
    'ID', 'Reason_absence', 'Reason_absence_name', 'Month_absence',
    'Month_absence_name', 'Day_week', 'Day_week_name', 'Seasons',
    'Seasons_name', 'Work_load_Average_day', 'Hit_target', 'Absenteeism_hours'
]

In [18]:
df_RRHH_abs = df_RRHH[col_absence].copy()

df_RRHH_abs

,ID,Reason_absence,Reason_absence_name,Month_absence,Month_absence_name,Day_week,Day_week_name,Seasons,Seasons_name,Work_load_Average_day,Hit_target,Absenteeism_hours
0,14,11.0,Sistema digestivo,5.0,Mayo,2,Lunes,2,Primavera,284.031,97,120
1,36,13.0,Sistema musculoesquelético,10.0,Octubre,4,Miércoles,4,Otoño,239.409,98,120
2,9,6.0,Sistema nervioso,1.0,Enero,3,Martes,1,Invierno,264.604,93,120
3,28,9.0,Sistema circulatorio,1.0,Enero,3,Martes,1,Invierno,230.290,92,112
4,9,12.0,Piel y tejido subcutáneo,9.0,Septiembre,3,Martes,3,Verano,222.196,99,112
...,...,...,...,...,...,...,...,...,...,...,...,...
839,14,11.0,Sistema digestivo,5.0,Mayo,2,Lunes,2,Primavera,284.031,97,120
840,36,13.0,Sistema musculoesquelético,10.0,Octubre,4,Miércoles,4,Otoño,239.409,98,120
841,9,6.0,Sistema nervioso,1.0,Enero,3,Martes,1,Invierno,264.604,93,120
842,28,9.0,Sistema circulatorio,1.0,Enero,3,Martes,1,Invierno,230.290,92,112
843,9,12.0,Piel y tejido subcutáneo,9.0,Septiembre,3,Martes,3,Verano,222.196,99,112

# Pregunta de negocio

**Analista de Perfil i Desempeño Professional:**  
- Quines característiques dels empleats estan associades amb un millor acompliment laboral
- com podem utilitzar aquesta informació per dissenyar estratègies de selecció, capacitació i retenció més efectives?

## Análisis descriptivo

### Distribución variable hit target (histograma y boxplot [outliers])

In [ ]:
plt.hist(df_RRHH['Hit_target'], bins=4)
plt.show()

In [ ]:
df_RRHH['Hit_target'].value_counts(normalize=True)*100

In [ ]:
df_RRHH['Hit_target'].unique()

In [ ]:
(df_RRHH['Hit_target']
 .value_counts(normalize=True)
 .mul(100)
 .plot(kind='bar'))

plt.ylabel('Porcentaje (%)')
plt.xlabel('Hit_target')
plt.title('Distribución de Hit_target')
plt.show()

In [ ]:
plt.boxplot(df_RRHH['Hit_target'])
plt.show()

Para saber el valor del outlier he mirado qué valores quedan fuera del cuartil Q1 y Q3.  
El valor **outlier es 81** (hay 23 registros), que es el mínimo, el siguiente valor es 88.

In [ ]:
col = df_RRHH['Hit_target']

Q1 = col.quantile(0.25)
Q3 = col.quantile(0.75)
IQR = Q3 - Q1

limit_inferior = Q1 - 1.5 * IQR
limit_superior = Q3 + 1.5 * IQR

outliers = df_RRHH[(col < limit_inferior) | (col > limit_superior)]

In [ ]:
outliers

### Para cada uno de los grupos de las otras variables

In [ ]:
df_RRHH.columns

#### Individuo

In [ ]:
for col in num:
    print(col)
    plt.hist(df_RRHH[col])
    plt.show()
    print(df_RRHH[col].nunique())
    print(df_RRHH[col].unique())
    print('----')

## Tamaño de muestra

In [ ]:
df_RRHH.info()

In [ ]:
# Función para calcular la moda de variables categóricas/temporales
def moda(x):
    m = x.dropna().mode()
    return m.iloc[0] if len(m) > 0 else np.nan

df_emp = df_RRHH.groupby('ID').agg(
    # Variable dependiente agregada a nivel empleado
    Hit_target_median=('Hit_target', 'median'),
    Hit_target_mean=('Hit_target', 'mean'),

    # Número de solicitudes / registros de ausencia por empleado
    num_absences=('ID', 'size'),

    # Variables numéricas del empleado
    Age=('Age', 'first'),
    Service_time=('Service_time', 'first'),
    Distance_Residence_Work=('Distance_Residence_Work', 'first'),
    Transportation_expense=('Transportation_expense', 'first'),

    # Variables que pueden variar por registro
    Absenteeism_hours_total=('Absenteeism_hours', 'sum'),
    Absenteeism_hours_median=('Absenteeism_hours', 'median'),
    # Work_load_Average_day_median=('Work_load_Average_day', 'median'),

    # Variables categóricas/dummy del empleado
    Disciplinary_failure=('Disciplinary_failure', 'first'),
    Education=('Education', 'first'),
    Son=('Son', 'first'),
    Social_drinker=('Social_drinker', 'first'),
    Social_smoker=('Social_smoker', 'first'),
    Pet=('Pet', 'first'),

    # Variables temporales: valor más frecuente por empleado
    Month_absence_mode=('Month_absence', moda),
    Seasons_mode=('Seasons', moda)
).reset_index()

In [ ]:
variables_grupo = [
    'Disciplinary_failure',
    'Education',
    'Son',
    'Social_drinker',
    'Social_smoker',
    'Pet'
]

for var in variables_grupo:
    #print(f"\n{var}")
    print(df_emp[var].value_counts(dropna=False))
    print(df_emp[var].value_counts(normalize=True, dropna=False) * 100)

Cleaning

In [ ]:
df_RRHH[df_RRHH['ID'] == 28][
    df_RRHH[df_RRHH['ID'] == 28].duplicated(keep=False)
]