# Data cleaning: Tourist_Accommodation22092025

In [23]:
import pandas as pd
import numpy as np
from pathlib import Path

In [24]:
# Importamos el CSV
input_path = Path("data") / "staySpain_raw_22092025.csv"
df = pd.read_csv(input_path)

In [25]:
# Hacemos una copia de df para no modificar el df original
df_clean = df.copy()

In [26]:
# Info de df_clean
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   apartment_id                 8000 non-null   int64
 1   name                         7997 non-null   object
 2   description                  7946 non-null   object
 3   host_id                      8000 non-null   int64
 4   neighbourhood_name           8000 non-null   object
 5   neighbourhood_district       4861 non-null   object
 6   room_type                    8000 non-null   object
 7   accommodates                 8000 non-null   int64
 8   bathrooms                    7957 non-null   float64
 9   bedrooms                     7961 non-null   float64
 10  beds                         7992 non-null   float64
 11  amenities_list               7983 non-null   object
 12  price                        7829 non-null   float64
 13  minimum_nights               8000 non-null   int64
 14  maximum_nights               8000 non-null   int64
 15  has_availability             7450 non-null   object
 16  availability_30              8000 non-null   int64
 17  availability_60              8000 non-null   int64
 18  availability_90              8000 non-null   int64
 19  availability_365             8000 non-null   int64
 20  number_of_reviews            8000 non-null   int64
 21  first_review_date            6386 non-null   object
 22  last_review_date             6385 non-null   object
 23  review_scores_rating         6304 non-null   float64
 24  review_scores_accuracy       6295 non-null   float64
 25  review_scores_cleanliness    6301 non-null   float64
 26  review_scores_checkin        6290 non-null   float64
 27  review_scores_communication  6299 non-null   float64
 28  review_scores_location       6289 non-null   float64
 29  review_scores_value          6289 non-null   float64
 30  is_instant_bookable          8000 non-null   object
 31  reviews_per_month            6386 non-null   float64
 32  country                      8000 non-null   object
 33  city                         8000 non-null   object
 34  insert_date                  8000 non-null   object
dtypes: float64(12), int64(10), object(13)
memory usage: 2.1+ MB

In [27]:
# Visualizamos todas las columnas en el output
pd.set_option("display.max_columns", None)

In [28]:
# Comprobamos si hay filas enteras duplicadas
df_clean.duplicated().any()

np.False_

In [29]:
# Comprobamos si hay duplicados en "apartment_id"
df_clean.duplicated(subset="apartment_id").sum()

np.int64(307)

In [30]:
# Buscamos duplicados en "apartment_id"
duplicados = df_clean[df_clean.duplicated("apartment_id", keep=False)]

In [31]:
# Ordenamos los registros para eliminar los duplicados con "insert_date" más antigua
df_clean = df_clean.sort_values("insert_date", ascending=False)\
                     .drop_duplicates("apartment_id", keep='first')\
                     .sort_index()

In [32]:
# Capitalizamos la primera letra de los valores en la columna "city" y "country"
df_clean["city"] = df_clean["city"].str.capitalize()
df_clean["country"] = df_clean["country"].str.capitalize()

In [33]:
df_clean.dtypes

apartment_id                     int64
name                            object
description                     object
host_id                          int64
neighbourhood_name              object
neighbourhood_district          object
room_type                       object
accommodates                     int64
bathrooms                      float64
bedrooms                       float64
beds                           float64
amenities_list                  object
price                          float64
minimum_nights                   int64
maximum_nights                   int64
has_availability                object
availability_30                  int64
availability_60                  int64
availability_90                  int64
availability_365                 int64
number_of_reviews                int64
first_review_date               object
last_review_date                object
review_scores_rating           float64
review_scores_accuracy         float64
review_scores_cleanliness      float64
review_scores_checkin          float64
review_scores_communication    float64
review_scores_location         float64
review_scores_value            float64
is_instant_bookable             object
reviews_per_month              float64
country                         object
city                            object
insert_date                     object
dtype: object

In [34]:
# Conversión de datos a date en las columnas que muestran fechas
df_clean["first_review_date"] = pd.to_datetime(df_clean['first_review_date'], errors='coerce', format='%d/%m/%Y')
df_clean["last_review_date"] = pd.to_datetime(df_clean['last_review_date'], errors='coerce', format='%d/%m/%Y')
df_clean["insert_date"] = pd.to_datetime(df_clean['insert_date'], errors='coerce', format='%d/%m/%Y')

In [35]:
# Conversión de float a int
df_clean["bathrooms"] = df_clean['bathrooms'].astype("Int64")
df_clean["bedrooms"] = df_clean['bedrooms'].astype("Int64")
df_clean["beds"] = df_clean['beds'].astype("Int64")

In [36]:
# Creamos una columna nueva para convertir "is_instant_bookable" en booleano
df_clean["is_instant_bookable_bool"] = df_clean["is_instant_bookable"].replace({"VERDADERO": True, "FALSO": False}).astype(bool)

df_clean.head()

C:\Users\buona\AppData\Local\Temp\ipykernel_12252\662236793.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean["is_instant_bookable_bool"] = df_clean["is_instant_bookable"].replace({"VERDADERO": True, "FALSO": False}).astype(bool)

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date,is_instant_bookable_bool
0,11964,A ROOM WITH A VIEW,Private bedroom in our attic apartment. Right ...,45553,Centro,NaN,Private room,2,2,1,1,"TV,Internet,Wifi,Air conditioning,Elevator,Buz...",400.0,3,365,VERDADERO,7,20,40,130,78,2010-01-02,2017-09-05,970.0,100.0,100.0,100.0,100.0,100.0,100.0,FALSO,75.0,Spain,Malaga,2018-07-31,False
1,21853,Bright and airy room,We have a quiet and sunny room with a good vie...,83531,C�rmenes,Latina,Private room,1,1,1,1,"TV,Internet,Wifi,Air conditioning,Kitchen,Free...",170.0,4,40,VERDADERO,0,0,0,162,33,2014-10-10,2018-07-15,920.0,90.0,90.0,100.0,100.0,80.0,90.0,FALSO,52.0,Spain,Madrid,2020-01-10,False
2,32347,Explore Cultural Sights from a Family-Friendly...,Open French doors and step onto a plant-filled...,139939,San Vicente,Casco Antiguo,Entire home/apt,4,1,2,2,"TV,Internet,Wifi,Air conditioning,Wheelchair a...",990.0,2,120,VERDADERO,26,31,31,270,148,2011-01-05,2019-07-22,980.0,100.0,100.0,100.0,100.0,100.0,100.0,VERDADERO,142.0,Spain,Sevilla,2019-07-29,True
3,35379,Double 02 CasanovaRooms Barcelona,Room at a my apartment. Kitchen and 2 bathroom...,152232,l'Antiga Esquerra de l'Eixample,Eixample,Private room,2,2,1,1,"TV,Internet,Wifi,Kitchen,Breakfast,Elevator,Bu...",400.0,2,730,VERDADERO,9,23,49,300,292,2012-03-13,2020-01-04,940.0,100.0,90.0,100.0,100.0,100.0,90.0,VERDADERO,306.0,Spain,Barcelona,2020-01-10,True
4,35801,Can Torras Farmhouse Studio Suite,Lay in bed & watch sunlight change the mood of...,153805,Quart,NaN,Private room,5,1,2,5,"Wifi,Pool,Free parking on premises,Breakfast,P...",900.0,1,180,VERDADERO,0,19,49,312,36,2011-07-08,2018-08-08,970.0,100.0,100.0,100.0,100.0,100.0,100.0,FALSO,39.0,Spain,Girona,2019-02-19,False

In [37]:
# Eliminamos la columna original
df_clean = df_clean.drop(columns="is_instant_bookable")

# Renombramos la nueva columna
df_clean = df_clean.rename({"is_instant_bookable_bool":"is_instant_bookable"}, axis=1)

df_clean.head()

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,country,city,insert_date,is_instant_bookable
0,11964,A ROOM WITH A VIEW,Private bedroom in our attic apartment. Right ...,45553,Centro,NaN,Private room,2,2,1,1,"TV,Internet,Wifi,Air conditioning,Elevator,Buz...",400.0,3,365,VERDADERO,7,20,40,130,78,2010-01-02,2017-09-05,970.0,100.0,100.0,100.0,100.0,100.0,100.0,75.0,Spain,Malaga,2018-07-31,False
1,21853,Bright and airy room,We have a quiet and sunny room with a good vie...,83531,C�rmenes,Latina,Private room,1,1,1,1,"TV,Internet,Wifi,Air conditioning,Kitchen,Free...",170.0,4,40,VERDADERO,0,0,0,162,33,2014-10-10,2018-07-15,920.0,90.0,90.0,100.0,100.0,80.0,90.0,52.0,Spain,Madrid,2020-01-10,False
2,32347,Explore Cultural Sights from a Family-Friendly...,Open French doors and step onto a plant-filled...,139939,San Vicente,Casco Antiguo,Entire home/apt,4,1,2,2,"TV,Internet,Wifi,Air conditioning,Wheelchair a...",990.0,2,120,VERDADERO,26,31,31,270,148,2011-01-05,2019-07-22,980.0,100.0,100.0,100.0,100.0,100.0,100.0,142.0,Spain,Sevilla,2019-07-29,True
3,35379,Double 02 CasanovaRooms Barcelona,Room at a my apartment. Kitchen and 2 bathroom...,152232,l'Antiga Esquerra de l'Eixample,Eixample,Private room,2,2,1,1,"TV,Internet,Wifi,Kitchen,Breakfast,Elevator,Bu...",400.0,2,730,VERDADERO,9,23,49,300,292,2012-03-13,2020-01-04,940.0,100.0,90.0,100.0,100.0,100.0,90.0,306.0,Spain,Barcelona,2020-01-10,True
4,35801,Can Torras Farmhouse Studio Suite,Lay in bed & watch sunlight change the mood of...,153805,Quart,NaN,Private room,5,1,2,5,"Wifi,Pool,Free parking on premises,Breakfast,P...",900.0,1,180,VERDADERO,0,19,49,312,36,2011-07-08,2018-08-08,970.0,100.0,100.0,100.0,100.0,100.0,100.0,39.0,Spain,Girona,2019-02-19,False

In [38]:
# # Repetimos proceso con has_availability pero con map() para mantener los NaN
mapping={"VERDADERO":True, "FALSO":False}
df_clean["has_availability"] = df_clean["has_availability"].map(mapping)

In [39]:
df_clean["has_availability"].isna().sum()

np.int64(534)

In [40]:
# Imputación de nombre para registros con NaN en "name"
df_clean['name'] = df_clean['name'].fillna(df_clean['room_type'] + ' ' + df_clean['neighbourhood_name'])

In [41]:
# Imputación de descripción para registros con NaN en "description"
df_clean['description'] = df_clean['description'].fillna(df_clean['name'])

# last part

In [42]:
#limpieza de caracteres raros.
df['neighbourhood_name'] = df['neighbourhood_name'].str.encode('latin1', errors='ignore').str.decode('utf-8', errors='ignore')

In [43]:
def reviews_format(df):
    """Formatear las variables de review"""
    df_clean = df.copy()

    df_clean['review_scores_rating'] = df_clean['review_scores_rating'] / 10
    df_clean['review_scores_accuracy'] = df_clean['review_scores_accuracy'] / 10
    df_clean['review_scores_cleanliness'] = df_clean['review_scores_cleanliness'] / 10
    df_clean['review_scores_checkin'] = df_clean['review_scores_checkin'] / 10
    df_clean['review_scores_communication'] = df_clean['review_scores_communication'] / 10
    df_clean['review_scores_location'] = df_clean['review_scores_location'] / 10
    df_clean['review_scores_value'] = df_clean['review_scores_value'] / 10

    return df_clean

In [44]:
def input_price(df, price, room_type, accommodates, neighbourhood_name):
    """Imputación de precios"""
    df_clean = df.copy()
    
    # Calcular la media según alojamiento, capacidad y localización
    avgs = df_clean.groupby([room_type, accommodates, neighbourhood_name])[price].transform('mean')
    df_clean[price] = df_clean[price].fillna(avgs)
    

    
    return df_clean

In [45]:
df_clean = reviews_format(df)

# Aplicacion input_price sobre el resultado anterior
df_clean = input_price(df_clean, 'price', 'room_type', 'accommodates', 'neighbourhood_name')

# Segunda imputación para lo que no pudo completarse con la media grupal
df_clean['price'] = df_clean['price'].fillna(df_clean['price'].mean())

In [46]:
import pandas as pd

print("Cargando datos crudos...")
input_path = "data/staySpain_raw_22092025.csv"
df = pd.read_csv(input_path)

print("Aplicando transformación: reviews_format")
df_clean = reviews_format(df)

print("Exportando archivos...")
output_path = "data/staySpain_clean_22092025.pkl"
output_path2 = "data/staySpain_clean_22092025.csv"

df_clean.to_pickle(output_path)
df_clean.to_csv(output_path2, index=False)

print(f"Datos transformados guardados en: {output_path}")
print(f"Datos transformados guardados en: {output_path2}")

Cargando datos crudos...
Aplicando transformación: reviews_format
Exportando archivos...
Datos transformados guardados en: data/staySpain_clean_22092025.pkl
Datos transformados guardados en: data/staySpain_clean_22092025.csv