In [1]:
import pandas as pd

In [20]:
input_path = r"data/staySpain_cleaned.pkl"
df = pd.read_pickle(input_path)

## PREGUNTA NEGOCI

### preu mitjà per tipus d'allotjament a cada ciutat

In [24]:
# Create crosstab with mean price
mean_price_per_room_type_and_city = pd.crosstab(index=df['city'], columns=df['room_type'], values=df['price'], aggfunc='mean')

# Display the crosstab
display(round(mean_price_per_room_type_and_city,2))

room_type  Entire home/apt  Hotel room  Private room  Shared room
city
barcelona          1300.94     1444.29        455.05       371.88
girona             1230.68      625.00        602.12          NaN
madrid              942.63      902.50        372.81       313.33
malaga              815.78      703.33        356.73       143.33
mallorca           1709.57     1401.67        700.25       493.33
menorca            1656.53         NaN        610.00          NaN
sevilla            1033.91      918.57        606.00       120.00
valencia            796.62      955.00        340.15       203.33

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6733 entries, 0 to 6999
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   apartment_id                 6733 non-null   int64
 1   name                         6730 non-null   object
 2   description                  6706 non-null   object
 3   host_id                      6733 non-null   int64
 4   neighbourhood_name           6733 non-null   object
 5   neighbourhood_district       4075 non-null   object
 6   room_type                    6733 non-null   object
 7   accommodates                 6733 non-null   int64
 8   bathrooms                    6701 non-null   Int64
 9   bedrooms                     6705 non-null   Int64
 10  beds                         6730 non-null   float64
 11  amenities_list               6717 non-null   object
 12  price                        6612 non-null   float64
 13  minimum_nights               6733 non-null   int64
 14  maximum_nights               6733 non-null   int64
 15  has_availability             6199 non-null   object
 16  availability_30              6733 non-null   int64
 17  availability_60              6733 non-null   int64
 18  availability_90              6733 non-null   int64
 19  availability_365             6733 non-null   int64
 20  number_of_reviews            6733 non-null   int64
 21  first_review_date            5525 non-null   datetime64[ns]
 22  last_review_date             5524 non-null   datetime64[ns]
 23  review_scores_rating         5454 non-null   float64
 24  review_scores_accuracy       5445 non-null   float64
 25  review_scores_cleanliness    5451 non-null   float64
 26  review_scores_checkin        5440 non-null   float64
 27  review_scores_communication  5449 non-null   float64
 28  review_scores_location       5439 non-null   float64
 29  review_scores_value          5439 non-null   float64
 30  is_instant_bookable          6733 non-null   object
 31  reviews_per_month            5525 non-null   float64
 32  country                      6733 non-null   object
 33  city                         6733 non-null   object
 34  insert_date                  6733 non-null   datetime64[ns]
dtypes: Int64(2), datetime64[ns](3), float64(10), int64(10), object(10)
memory usage: 1.9+ MB

## NULOS

In [14]:
# Create crosstab for null counts in 'price'
crosstab_nulls = pd.crosstab(df['city'], df['room_type'], values=df['price'].isnull(), aggfunc='sum')

display(crosstab_nulls)

room_type  Entire home/apt  Hotel room  Private room  Shared room
city
barcelona             21.0         0.0           3.0          2.0
girona                15.0         0.0           0.0          NaN
madrid                 8.0         1.0           1.0          0.0
malaga                 1.0         0.0           0.0          0.0
mallorca              58.0         1.0           1.0          0.0
menorca                4.0         NaN           0.0          NaN
sevilla                1.0         0.0           1.0          0.0
valencia               2.0         0.0           1.0          0.0

In [ ]:
En valores absolutos,
Los nulos están concentrados en
MALLORCA - Entire home/apt : 58   (5.76%)
BARCELONA - Entire home/apt : 21  (2.21%)
GIRONA - Entire home/apt: 15   (1.45%)

In [12]:
# Create crosstab for total counts
crosstab_total = pd.crosstab(df['city'], df['room_type'])

display(crosstab_total)

room_type  Entire home/apt  Hotel room  Private room  Shared room
city
barcelona              950           7          1066           18
girona                1029           4            52            0
madrid                 901           5           475           15
malaga                 278           3            55            3
mallorca              1006           7            80            3
menorca                128           0            10            0
sevilla                262           7            71            1
valencia               226           2            66            3

In [13]:
# Calculate the proportion of nulls
proportion_nulls = crosstab_nulls.div(crosstab_total).fillna(0)

display(proportion_nulls*100) # shows percentage

room_type  Entire home/apt  Hotel room  Private room  Shared room
city
barcelona         2.210526    0.000000      0.281426    11.111111
girona            1.457726    0.000000      0.000000     0.000000
madrid            0.887902   20.000000      0.210526     0.000000
malaga            0.359712    0.000000      0.000000     0.000000
mallorca          5.765408   14.285714      1.250000     0.000000
menorca           3.125000    0.000000      0.000000     0.000000
sevilla           0.381679    0.000000      1.408451     0.000000
valencia          0.884956    0.000000      1.515152     0.000000

Hotel Room - Madrid (20%)
Hotel Room - Mallorca (14.28%)
Sharted Room - Barcelona (11.11% PERO hay muy poca muestra)

In [25]:
nulos_df = df[df.price.isna()]

In [19]:
nulos_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 121 entries, 16 to 6993
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   apartment_id                 121 non-null    int64
 1   name                         121 non-null    object
 2   description                  120 non-null    object
 3   host_id                      121 non-null    int64
 4   neighbourhood_name           121 non-null    object
 5   neighbourhood_district       41 non-null     object
 6   room_type                    121 non-null    object
 7   accommodates                 121 non-null    int64
 8   bathrooms                    121 non-null    Int64
 9   bedrooms                     121 non-null    Int64
 10  beds                         120 non-null    float64
 11  amenities_list               119 non-null    object
 12  price                        0 non-null      float64
 13  minimum_nights               121 non-null    int64
 14  maximum_nights               121 non-null    int64
 15  has_availability             115 non-null    object
 16  availability_30              121 non-null    int64
 17  availability_60              121 non-null    int64
 18  availability_90              121 non-null    int64
 19  availability_365             121 non-null    int64
 20  number_of_reviews            121 non-null    int64
 21  first_review_date            77 non-null     datetime64[ns]
 22  last_review_date             77 non-null     datetime64[ns]
 23  review_scores_rating         77 non-null     float64
 24  review_scores_accuracy       77 non-null     float64
 25  review_scores_cleanliness    77 non-null     float64
 26  review_scores_checkin        77 non-null     float64
 27  review_scores_communication  77 non-null     float64
 28  review_scores_location       77 non-null     float64
 29  review_scores_value          77 non-null     float64
 30  is_instant_bookable          121 non-null    object
 31  reviews_per_month            77 non-null     float64
 32  country                      121 non-null    object
 33  city                         121 non-null    object
 34  insert_date                  121 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](3), float64(10), int64(10), object(10)
memory usage: 34.3+ KB

In [26]:
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns

In [27]:
nulos_df

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date
16,101580,Big house in PARADISE,Luxury and quiet villa in Cala Canyelles (2km ...,532063,Lloret de Mar,NaN,Entire home/apt,16,4,4,12.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Poo...",NaN,2,30,VERDADERO,22,52,82,237,14,2017-05-28,2018-10-14,99.0,10.0,10.0,10.0,10.0,9.0,10.0,VERDADERO,73.0,spain,girona,2018-12-22
55,361488,RETIRO PARK2 CHALET INDUSTRIAL-CHIC,CHALET INDUSTRIAL-CHIC RETIRO PARK2 This vill...,1732442,Ni�o Jes�s,Retiro,Entire home/apt,6,3,3,3.0,"TV,Internet,Wifi,Kitchen,Free parking on premi...",NaN,5,365,VERDADERO,0,0,0,0,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,madrid,2019-04-11
85,474387,"Des Artistes 716, wifi, central P",THE PRICE IS FOR EXCLUSIVE USE FOR A MAX. OF 1...,1614471,el Fort Pienc,Eixample,Entire home/apt,11,2,5,11.0,"Wireless Internet,Wheelchair accessible,Smokin...",NaN,3,30,NaN,8,38,68,340,16,2013-04-22,2016-02-25,81.0,9.0,9.0,10.0,9.0,9.0,8.0,FALSO,35.0,spain,barcelona,2017-02-09
160,721378,Big and nice apartment near to Sagrada Familia,Beautiful 4 bedroom apartment in a superb posi...,3724467,el Fort Pienc,Eixample,Entire home/apt,6,2,4,5.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Paid...",NaN,3,365,VERDADERO,15,35,65,340,3,2018-03-03,2019-02-27,93.0,10.0,9.0,10.0,8.0,9.0,9.0,VERDADERO,16.0,spain,barcelona,2019-09-17
161,721509,P3 Valencia Apartment 1 bedroom,"Lovely one-bedroom apartment, located on a fir...",3724467,la Dreta de l'Eixample,Eixample,Entire home/apt,4,1,1,1.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Kit...",NaN,3,365,VERDADERO,23,48,78,158,1,2018-04-18,2018-04-18,80.0,6.0,10.0,10.0,10.0,8.0,6.0,VERDADERO,10.0,spain,barcelona,2018-05-14
308,1071662,LUXURY SEAVIEW S'AGARO COSTA BRAVA,BEST HOLIDAY ON THE COSTA BRAVA THAT YOU CAN T...,1830359,Castell-Platja d'Aro,NaN,Entire home/apt,7,2,3,6.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Free par...",NaN,14,60,VERDADERO,23,53,83,358,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,girona,2018-12-22
476,1648617,Holiday House in CALA TUENT,Historic finca with private access to the sea....,8746555,Escorca,NaN,Entire home/apt,12,5,6,12.0,"TV,Cable TV,Wifi,Pool,Kitchen,Free parking on ...",NaN,3,1125,VERDADERO,6,15,24,291,38,2014-07-14,2019-06-10,99.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,63.0,spain,mallorca,2019-06-27
633,2531084,In front of the Giralda,"This apartment, situated in �Calle Alemanes�, ...",4653961,Santa Cruz,Casco Antiguo,Entire home/apt,4,1,1,2.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Paid...",NaN,3,1124,VERDADERO,20,48,66,307,57,2014-05-30,2018-07-27,97.0,10.0,10.0,10.0,10.0,10.0,10.0,VERDADERO,112.0,spain,sevilla,2018-07-31
707,2963691,Modern villa in Portals with pool and sea view,"Only 5 min to the nearest beach, to the tennis...",15124488,Calvi�,NaN,Entire home/apt,8,4,4,8.0,"TV,Internet,Wifi,Air conditioning,Pool,Kitchen...",NaN,4,1125,VERDADERO,30,58,61,332,27,2015-08-19,2019-08-31,99.0,10.0,10.0,10.0,10.0,10.0,9.0,FALSO,46.0,spain,mallorca,2020-05-28
743,3107710,1563 - AB Pla�a Espanya 2-1 - Classy 3-Bedroom...,This modish three bedroom holiday apartment in...,4459553,la Nova Esquerra de l'Eixample,Eixample,Entire home/apt,6,2,3,6.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Elev...",NaN,2,330,VERDADERO,9,34,64,339,11,2016-06-20,2018-08-20,80.0,8.0,9.0,8.0,8.0,9.0,8.0,VERDADERO,38.0,spain,barcelona,2018-11-07
780,3275634,Palacete en el centro de Valencia!!,Gran vivienda tipo palacete de 300 metros de v...,535881,EL CARME,CIUTAT VELLA,Entire home/apt,10,3,5,10.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Whe...",NaN,1,1125,VERDADERO,30,60,90,365,4,2016-04-11,2016-08-14,73.0,8.0,9.0,10.0,9.0,7.0,7.0,FALSO,8.0,spain,valencia,2020-02-29
929,3972514,Beautiful romantic Finca in the wine area,Santa Lucia is a perfect holiday paradise for ...,20589712,Binissalem,NaN,Entire home/apt,10,5,5,10.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Poo...",NaN,3,1125,VERDADERO,9,9,10,169,6,2015-05-05,2019-04-14,100.0,10.0,10.0,10.0,10.0,9.0,10.0,FALSO,12.0,spain,mallorca,2019-05-27
964,4254382,EXCLUSIVE VILLA NEAR PALMA WITH BOOKABLE BREAK...,Exclusive and luxury villa exquisitely decorat...,13210167,Palma de Mallorca,NaN,Entire home/apt,12,6,6,12.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Free par...",NaN,3,365,VERDADERO,0,0,0,0,31,2015-02-16,2018-08-20,99.0,10.0,10.0,10.0,10.0,9.0,9.0,FALSO,64.0,spain,mallorca,2019-01-28
1065,4970202,Perfect apartment BCN city center,"Beautiful apartment in the city center, with t...",18755624,Sant Antoni,Eixample,Entire home/apt,6,2,3,5.0,"Internet,Wifi,Air conditioning,Kitchen,Smoking...",NaN,4,30,VERDADERO,0,0,0,0,2,2015-03-08,2016-02-12,100.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,5.0,spain,barcelona,2018-04-12
1161,5429715,Cal Pubill de Ciuret 35pax,Cal Pubill de Ciuret �s una de les grans masie...,20320423,Vidr�,NaN,Entire home/apt,16,9,14,30.0,"TV, Indoor fireplace, Pool, Iron, Crib, Hair d...",NaN,2,1125,VERDADERO,24,54,77,296,1,2019-12-08,2019-12-08,100.0,10.0,10.0,10.0,10.0,10.0,10.0,VERDADERO,9.0,spain,girona,2020-10-28
1252,5936519,Luxus Villa zum Verlieben,Die Villa wurde in den letzten 2 Jahren komple...,30823800,Calvi�,NaN,Entire home/apt,8,5,5,5.0,"TV,Internet,Wifi,Air conditioning,Pool,Kitchen...",NaN,3,1125,VERDADERO,29,59,89,315,7,2016-04-30,2018-10-07,100.0,10.0,10.0,9.0,10.0,10.0,10.0,VERDADERO,22.0,spain,mallorca,2018-12-18
1270,6035889,Lugaris Beach Family Apartment,This spacious apartment with design furniture ...,375625,el Poblenou,Sant Mart�,Entire home/apt,6,3,2,3.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Whe...",NaN,1,28,VERDADERO,21,51,81,351,59,2015-07-13,2020-03-11,94.0,10.0,10.0,10.0,10.0,9.0,9.0,VERDADERO,10.0,spain,barcelona,2020-05-11
1280,6112685,Gro�e Luxus Finca bei Arta,individuell und sehr exklusiv Diese sehr indiv...,3209220,Art�,NaN,Entire home/apt,12,5,6,9.0,"TV,Cable TV,Wireless Internet,Air conditioning...",NaN,5,1125,NaN,28,58,88,363,1,2016-07-16,2016-07-16,100.0,8.0,8.0,8.0,10.0,10.0,10.0,FALSO,12.0,spain,mallorca,2017-03-15
1294,6191590,CoastalVillas - Villa Dali,This stunning villa is located in the quiet re...,31707257,Lloret de Mar,NaN,Entire home/apt,12,4,6,7.0,"TV,Wifi,Pool,Kitchen,Free parking on premises,...",NaN,7,1125,VERDADERO,27,50,59,149,1,2018-05-26,2018-05-26,80.0,8.0,8.0,10.0,10.0,10.0,10.0,FALSO,11.0,spain,girona,2019-02-19
1296,6191684,"CoastalVillas - Villa Gaudi AC, exterior spa",Villa Gaudi is located in a quiet street in th...,31707257,Lloret de Mar,NaN,Entire home/apt,12,4,6,7.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Free par...",NaN,7,1125,VERDADERO,11,41,70,77,1,2018-09-01,2018-09-01,100.0,10.0,10.0,10.0,8.0,10.0,10.0,FALSO,8.0,spain,girona,2019-09-30
1394,6695341,charming 200 year old �finca�,Located in the heart of the wine growing count...,3774266,Consell,NaN,Entire home/apt,16,7,10,16.0,"TV,Internet,Wireless Internet,Air conditioning...",NaN,5,1125,NaN,0,0,0,0,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,mallorca,2017-03-15
1650,7948633,Mallorca desconocida,"La casa est� muy cerca del pueblo de Lloseta, ...",41916589,Lloseta,NaN,Entire home/apt,16,8,1,16.0,NaN,NaN,1,1125,VERDADERO,0,0,0,0,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,mallorca,2019-06-27
1678,8110333,Apartment in Barcelona 1],The apartment is located in the Gothic distric...,10049157,el Barri G�tic,Ciutat Vella,Entire home/apt,16,3,5,13.0,"Internet,Wireless Internet,Kitchen,Heating,Was...",NaN,2,1125,NaN,17,37,56,311,22,2016-01-03,2017-04-16,85.0,9.0,9.0,10.0,9.0,10.0,8.0,VERDADERO,134.0,spain,barcelona,2017-05-07
1699,8345256,Awsome space in the downtown.,Spacious 120 square meters apartment with all ...,43988161,Justicia,Centro,Entire home/apt,4,1,2,1.0,"Oven, High chair, Cooking basics, Essentials, ...",NaN,2,1125,VERDADERO,30,60,90,365,48,2015-09-21,2018-07-15,98.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,75.0,spain,madrid,2020-12-17
1834,9473403,Modern Loft w/View Calle Fuencarral,Bright sunny apartment two balconies views....,28404781,Justicia,Centro,Entire home/apt,3,1,0,1.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Free...",NaN,365,1125,VERDADERO,0,0,0,66,78,2015-12-23,2017-09-25,98.0,10.0,10.0,10.0,10.0,10.0,10.0,VERDADERO,20.0,spain,madrid,2019-03-08
1837,9484967,Ca'n Mussol finca Sa Pobla 040,"Rustic Villa at the north of the island, come ...",3893191,Sa Pobla,NaN,Entire home/apt,6,2,3,5.0,"Oven, Wifi, Garden or backyard, Coffee maker, ...",NaN,1,1125,VERDADERO,30,60,90,365,2,2016-07-31,2020-08-25,80.0,7.0,8.0,8.0,7.0,8.0,7.0,VERDADERO,4.0,spain,mallorca,2020-09-19
1970,10541401,Fantastic Villa 80 mts from the sea,Detached Villa on a garden of 27.000 square fe...,45908413,Ciutadella de Menorca,NaN,Entire home/apt,10,6,5,9.0,"Private entrance, Hot water, Pool, Coffee make...",NaN,4,1125,VERDADERO,28,58,88,324,4,2018-07-11,2019-07-25,95.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,14.0,spain,menorca,2020-11-30
1993,10724048,Single room near Sagrada Familia,We are a young couple working in tourism secto...,39790779,el Clot,Sant Mart�,Private room,1,1,1,1.0,"TV,Cable TV,Internet,Wifi,Kitchen,Elevator,Buz...",NaN,3,1125,VERDADERO,0,0,0,0,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,barcelona,2019-12-10
2043,11107557,Alzina Living Villa Son Mas - Tourist Licence,"Son Mas, rural in central Palma, 7 mins walkin...",13627915,Palma de Mallorca,NaN,Entire home/apt,16,8,8,16.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Free par...",NaN,4,100,VERDADERO,5,9,24,298,27,2016-07-12,2018-05-20,96.0,10.0,9.0,10.0,10.0,9.0,10.0,FALSO,108.0,spain,mallorca,2018-07-29
2058,11164099,Impressive avant-garde villa with private beac...,"Villa with 8 double bedrooms, 5 bathrooms, air...",5558099,Alc�dia,NaN,Entire home/apt,12,5,8,12.0,"Hot water, Free parking on premises, Air condi...",NaN,7,1125,VERDADERO,22,22,22,259,1,2019-09-14,2019-09-14,100.0,10.0,10.0,10.0,10.0,10.0,10.0,VERDADERO,7.0,spain,mallorca,2020-10-21
2064,11196074,Finca can Domingo Es Trenc beach,"At the heart of the Balearic archipelago, sout...",16964951,Campos,NaN,Entire home/apt,16,12,10,16.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Poo...",NaN,3,1125,VERDADERO,13,38,68,322,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,mallorca,2019-11-28
2089,11356663,Central Valencia,"Very beautiful views, and walking distance to ...",59485697,LA XEREA,CIUTAT VELLA,Entire home/apt,4,1,2,3.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Free...",NaN,100,100,VERDADERO,0,0,0,212,66,2016-05-04,2019-01-01,89.0,9.0,9.0,9.0,9.0,10.0,9.0,FALSO,163.0,spain,valencia,2019-09-01
2116,11488053,Villa Caputo,Neutrally decorated throughout Villa Caputo is...,24926928,Pollen�a,NaN,Entire home/apt,10,4,5,7.0,"Smoke alarm, Oven, Pack u2019n Play/travel cri...",NaN,5,1125,VERDADERO,23,53,83,358,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,mallorca,2020-09-19
2393,12980733,Superbe villa contemporaine,During your stay you have access to the entire...,24708286,Lloret de Mar,NaN,Entire home/apt,14,4,5,9.0,"TV,Internet,Wifi,Air conditioning,Wheelchair a...",NaN,2,1125,VERDADERO,22,43,52,256,18,2016-07-16,2019-09-08,89.0,9.0,9.0,9.0,9.0,9.0,9.0,FALSO,4.0,spain,girona,2020-03-26
2482,13242295,Semi detached Villa in Palma city Private Pool,Lugares de inter�s: parques. Te va a encantar ...,74415548,Palma de Mallorca,NaN,Entire home/apt,8,3,5,6.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Free par...",NaN,5,1125,VERDADERO,0,0,0,0,9,2016-07-25,2018-11-30,97.0,10.0,10.0,10.0,10.0,10.0,9.0,VERDADERO,23.0,spain,mallorca,2019-09-28
2491,13259140,Nice double room in flat overlooking Montjuic,"Close to Poble Espanyol, CaixaForum, Font M�gi...",11928283,el Poble Sec,Sants-Montju�c,Private room,2,1,1,1.0,"Wifi,Kitchen,Elevator,Washer,Essentials,Shampo...",NaN,2,20,VERDADERO,0,0,0,0,7,2016-06-03,2016-07-04,94.0,10.0,9.0,9.0,10.0,9.0,9.0,FALSO,21.0,spain,barcelona,2019-02-06
2611,13651387,Exclusive Apartment with views to La Pedrera,100% REDECORATED IN MARCH�2018! Right in the h...,43565515,la Dreta de l'Eixample,Eixample,Entire home/apt,9,4,5,5.0,"TV,Wifi,Air conditioning,Kitchen,Elevator,Fami...",NaN,2,1125,VERDADERO,13,22,33,290,2,2016-10-08,2018-05-11,100.0,10.0,10.0,9.0,10.0,10.0,10.0,VERDADERO,1.0,spain,barcelona,2018-05-14
2643,13722943,habitacion compartida 2,Mi alojamiento es bueno para aventureros.,78488982,Sant Gervasi - Galvany,Sarri�-Sant Gervasi,Shared room,1,1,1,1.0,NaN,NaN,1,1125,NaN,0,0,0,0,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,barcelona,2017-02-09
2646,13742696,Modern & Cozy Apartment in Rambla Catalunya,"RAMBLA CATALUNYA VINTAGE, is a comfortable apa...",43565515,la Dreta de l'Eixample,Eixample,Entire home/apt,6,2,2,3.0,"TV,Cable TV,Wifi,Air conditioning,Kitchen,Paid...",NaN,2,1125,VERDADERO,7,30,44,275,3,2018-06-17,2019-12-31,80.0,9.0,8.0,9.0,10.0,10.0,9.0,VERDADERO,15.0,spain,barcelona,2020-02-16
2674,13792358,GAMUNDI,INSTALACIONES GENERALES Swimming pool Inter...,43337979,Muro,NaN,Entire home/apt,16,4,6,8.0,"TV,Cable TV,Wifi,Air conditioning,Pool,Kitchen...",NaN,7,1125,VERDADERO,7,27,49,194,1,2017-08-28,2017-08-28,100.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,4.0,spain,mallorca,2019-09-28
2704,13855168,"Mas de Xax�s, alojamiento para 23 personas",Lugares de inter�s: Paisajes con increibles vi...,81843163,Camprodon,NaN,Entire home/apt,16,8,9,16.0,"TV,Wifi,Breakfast,Indoor fireplace,Heating,Fam...",NaN,2,1125,VERDADERO,0,0,0,230,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,girona,2018-04-21
2798,14124456,Villa con espectaculares vistas al mar en Menorca,Binibarri es una moderna y espectacular villa ...,85168184,Sant Llu�s,NaN,Entire home/apt,8,4,4,7.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Free par...",NaN,1,1125,VERDADERO,30,48,55,284,9,2016-08-24,2017-10-28,98.0,10.0,10.0,10.0,10.0,10.0,9.0,FALSO,45.0,spain,menorca,2018-04-21
2864,14299477,Villa Laurax. Chalet independiente..,"Espectacular Villa Laurax , con piscina para u...",87345986,Ciutadella de Menorca,NaN,Entire home/apt,8,3,3,7.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Free par...",NaN,1,1125,VERDADERO,16,33,35,297,19,2018-02-04,2019-04-21,93.0,10.0,9.0,10.0,10.0,10.0,9.0,FALSO,126.0,spain,menorca,2019-05-01
2953,14700232,La Casa de las Vistas,The property is a spectacular 7.000 sq. m. sta...,91420568,Palma de Mallorca,NaN,Entire home/apt,10,5,5,7.0,"TV,Cable TV,Internet,Wifi,Wheelchair accessibl...",NaN,6,1125,VERDADERO,23,53,83,358,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,mallorca,2020-05-28
2982,14904922,Villa/Townhouse with amazing views in Palma,Luxury hideaway with stunning views of bay of ...,13351845,Palma de Mallorca,NaN,Entire home/apt,8,4,4,8.0,"TV,Internet,Wifi,Air conditioning,Pool,Kitchen...",NaN,5,1125,VERDADERO,8,38,68,343,15,2017-02-02,2018-09-03,98.0,10.0,10.0,10.0,10.0,9.0,9.0,VERDADERO,76.0,spain,mallorca,2018-09-18
3020,15033343,"Son Siliano, countryhouse in Sant Llorens, Mal...",Holiday house with private pool in Sant Lloren...,81580920,Sant Lloren� des Cardassar,NaN,Entire home/apt,10,9,9,13.0,"Oven, Wifi, Garden or backyard, Coffee maker, ...",NaN,1,1125,VERDADERO,23,53,83,358,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VERDADERO,NaN,spain,mallorca,2020-09-19
3067,15188771,Casa Pi - Best sea and port views Puerto Andratx,Beautiful mediterranean Villa with stunning se...,35118197,Andratx,NaN,Entire home/apt,9,4,5,9.0,"TV,Internet,Wifi,Air conditioning,Pool,Kitchen...",NaN,5,30,VERDADERO,23,53,74,128,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,mallorca,2018-04-18
3088,15241162,Madrid Rent 6,"Tres habitaciones, dos cuartos de ba�o, equipa...",96502620,Almendrales,Usera,Entire home/apt,6,2,3,5.0,"Iron, TV, Crib, Dishwasher, Cooking basics, He...",NaN,2,1125,VERDADERO,0,0,0,28,9,2016-11-06,2020-08-10,88.0,9.0,10.0,9.0,10.0,9.0,8.0,VERDADERO,18.0,spain,madrid,2020-11-06
3096,15262802,1554 - AB Passeig de Gr�cia Pelai - Modern Cit...,"This spacious apartment in Barcelona, recently...",4459553,el Raval,Ciutat Vella,Entire home/apt,7,1,2,5.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Elev...",NaN,3,330,VERDADERO,10,23,50,306,29,2016-12-29,2018-11-19,86.0,9.0,9.0,8.0,9.0,10.0,9.0,VERDADERO,122.0,spain,barcelona,2018-12-10
3178,15644356,Luxury Villa Mongoda VIP,Superb luxury villa in the most privileged are...,23347498,Lloret de Mar,NaN,Entire home/apt,9,5,5,5.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Poo...",NaN,4,1124,VERDADERO,29,31,31,272,1,2017-08-14,2017-08-14,100.0,10.0,10.0,10.0,8.0,10.0,10.0,FALSO,4.0,spain,girona,2019-09-30
3186,15670908,Son Sastre Muro Villa 024,Majestic Majorcan villa with beautiful garden ...,3893191,Muro,NaN,Entire home/apt,8,3,4,5.0,"Garden or backyard, Free street parking, Stove...",NaN,1,1125,VERDADERO,30,60,90,275,2,2018-12-20,2019-08-24,100.0,10.0,10.0,8.0,8.0,8.0,8.0,VERDADERO,8.0,spain,mallorca,2021-01-16
3211,15787767,MALAGA CENTER DE LUXE FLAT,"Central apartment, completely renovated and fu...",88872403,Centro,NaN,Entire home/apt,6,1,2,2.0,"First aid kit, Washer, Hangers, Wifi, Paid par...",NaN,1,1125,VERDADERO,0,0,0,167,37,2016-11-12,2019-08-18,91.0,9.0,10.0,9.0,10.0,9.0,9.0,VERDADERO,77.0,spain,malaga,2020-10-30
3242,15882695,FILIPINAS-house with swimming pool-Tamariu-Cos...,Set in the quiet residential area Aigua Gelid...,102326201,Palafrugell,NaN,Entire home/apt,8,5,4,6.0,"TV,Internet,Wifi,Pool,Kitchen,Free parking on ...",NaN,1,1125,VERDADERO,0,0,0,7,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VERDADERO,NaN,spain,girona,2019-05-29
3247,15883302,Ca's Misser,"Beautiful rustic farm with a total area of 21,...",102986764,Algaida,NaN,Entire home/apt,29,8,14,22.0,"TV,Cable TV,Internet,Wifi,Air conditioning,Poo...",NaN,1,1125,VERDADERO,5,19,27,218,3,2019-05-27,2019-09-18,80.0,8.0,9.0,9.0,6.0,9.0,7.0,VERDADERO,32.0,spain,mallorca,2020-02-29
3263,15938138,RUSTIC VILLA ON THE SEA FRONT. AMAZING VIEWS,Great rustic Catalan style house on the Costa ...,15181474,Palam�s,NaN,Entire home/apt,12,7,8,12.0,"TV,Wifi,Pool,Kitchen,Free parking on premises,...",NaN,2,1125,VERDADERO,29,59,89,337,5,2016-12-29,2018-07-28,95.0,10.0,10.0,10.0,10.0,10.0,9.0,FALSO,19.0,spain,girona,2019-02-19
3287,16064297,Impresionante lujo en la mejor finca de Madrid,Piso palaciego de 250 m2. Enorme sal�n de 70m2...,65778179,Justicia,Centro,Entire home/apt,7,5,3,7.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Door...",NaN,4,1125,VERDADERO,0,5,5,258,10,2016-12-26,2018-01-13,98.0,10.0,10.0,10.0,10.0,10.0,9.0,VERDADERO,39.0,spain,madrid,2019-02-06
3451,16541989,Casa Linda,Only a few meters from the quiet beach �Llenai...,107383413,Pollen�a,NaN,Entire home/apt,10,6,5,7.0,"TV,Wifi,Air conditioning,Pool,Kitchen,Heating,...",NaN,1,1125,VERDADERO,2,2,10,278,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VERDADERO,NaN,spain,mallorca,2019-12-31
3541,16880095,Apartment in Barcelona,Beautiful flat in the downtown with complete f...,112544099,la Vila de Gr�cia,Gr�cia,Entire home/apt,2,1,1,1.0,"TV,Cable TV,Wireless Internet,Kitchen,Heating,...",NaN,1,1125,VERDADERO,30,60,90,365,0,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,barcelona,2018-02-07
3624,17165421,"Beautiful villa, stunning sea views, private pool",The Port House is a four bedroom villa located...,115464145,S�ller,NaN,Entire home/apt,8,5,4,9.0,"Dishes and silverware, Pool, Room-darkening sh...",NaN,5,1125,VERDADERO,0,5,35,275,8,2017-05-26,2017-09-17,98.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,19.0,spain,mallorca,2020-11-08