# Data cleaning Desafío 1

## Import libraries

In [1]:
import pandas as pd

# Read files

In [2]:
DATA_RRHH_RAW_FILE = '../Data/raw/raw_data.csv'

In [3]:
df_RRHH = pd.read_csv(DATA_RRHH_RAW_FILE)
df_RRHH.sample(5)

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
155,22,1,10,2,4,179,26,9,30,"265,017",...,0,3,0,0,0,0,56,171,19,8
463,33,23,10,4,4,248,25,14,47,"253,465",...,0,1,2,0,0,1,86,165,32,2
484,14,28,2,5,2,155,12,14,34,"302,585",...,0,1,2,1,0,0,95,196,25,2
10,22,1,10,4,4,179,26,9,30,"265,017",...,0,3,0,0,0,0,56,171,19,64
670,34,28,5,2,3,118,10,10,37,"246,074",...,0,1,0,0,0,0,83,172,28,1

# Data cleaning

In [6]:
df_RRHH.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,740.0,18.017568,11.021247,1.0,9.0,18.0,28.0,36.0
Reason_absence,740.0,19.216216,8.433406,0.0,13.0,23.0,26.0,28.0
Month_absence,740.0,6.324324,3.436287,0.0,3.0,6.0,9.0,12.0
Day_week,740.0,3.914865,1.421675,2.0,3.0,4.0,5.0,6.0
Seasons,740.0,2.544595,1.111831,1.0,2.0,3.0,4.0,4.0
Transportation_expense,740.0,221.329730,66.952223,118.0,179.0,225.0,260.0,388.0
Distance_Residence_Work,740.0,29.631081,14.836788,5.0,16.0,26.0,50.0,52.0
Service_time,740.0,12.554054,4.384873,1.0,9.0,13.0,16.0,29.0
Age,740.0,36.450000,6.478772,27.0,31.0,37.0,40.0,58.0
Hit_target,740.0,94.587838,3.779313,81.0,93.0,95.0,97.0,100.0
Disciplinary_failure,740.0,0.054054,0.226277,0.0,0.0,0.0,0.0,1.0
Education,740.0,1.291892,0.673238,1.0,1.0,1.0,1.0,4.0
Son,740.0,1.018919,1.098489,0.0,0.0,1.0,2.0,4.0
Social_drinker,740.0,0.567568,0.495749,0.0,0.0,1.0,1.0,1.0
Social_smoker,740.0,0.072973,0.260268,0.0,0.0,0.0,0.0,1.0
Pet,740.0,0.745946,1.318258,0.0,0.0,0.0,1.0,8.0
Weight,740.0,79.035135,12.883211,56.0,69.0,83.0,89.0,108.0
Height,740.0,172.114865,6.034995,163.0,169.0,170.0,172.0,196.0
Body_mass_index,740.0,26.677027,4.285452,19.0,24.0,25.0,31.0,38.0
Absenteeism_hours,740.0,6.924324,13.330998,0.0,2.0,3.0,8.0,120.0